Sutils.H
static void ltrim(std::string &s)
String trim white-space from start (in place version)
Referenced by ltrim_copy, trim.
static std::string ltrim_copy(std::string s)
String trim white space from start (new copy)
References ltrim.
static void rtrim(std::string &s)
String trim white-space string from end (in place version)
Referenced by rtrim_copy, trim.
static std::string rtrim_copy(std::string s)
String trim white space from end (new copy)
References rtrim.
std::vector< std::string > str_split(const std::string &s, char delimiter)
Split string on a character delimiter.
std::string str_to_lower(const std::string &s)
Return a lower case copy.
std::string str_to_upper(const std::string &s)
Return an upper case copy.
static void trim(std::string &s)
String trim white-spacefrom both ends (in place)
References ltrim, rtrim.
Referenced by AsciiHisto< T >::AsciiHisto, trim_copy.
static std::string trim_copy(std::string s)
String trim white space from both ends (new copy)
References trim.