Sphere
string Sphere::cache_file
int Sphere::cmap
double Sphere::dfac
int Sphere::diverge
double Sphere::dtime
bool Sphere::logr
string Sphere::model_file
int Sphere::noff
int Sphere::numr
int Sphere::nums
SLGridSphPtr Sphere::ortho
Referenced by d_r_to_xi, d_xi_to_r, r_to_xi, xi_to_r.
bool Sphere::plummer
Referenced by make_model.
bool Sphere::recompute
Referenced by determine_coefficients.
double Sphere::rmap
double Sphere::rsphSL
double Sphere::tnext
Referenced by determine_coefficients.
const std::set<std::string> Sphere::valid_keys
Valid keys for YAML configurations.
double Sphere::d_r_to_xi(double r)
References ortho, r_to_xi.
double Sphere::d_xi_to_r(double x)
References ortho.
void Sphere::get_dens(int lmax, int nmax, double r, Eigen::MatrixXd &p, int tid)
Get derivative of potential lmax is the maximum harmonic order nmax is the maximum radial order r is the evaluation radius d will be returned array in harmonics l and radial order n for the density tid is the thread enumerator that allows the function to provide some thread safety
void Sphere::get_dpotl(int lmax, int nmax, double r, Eigen::MatrixXd &p, Eigen::MatrixXd &dp, int tid)
Get derivative of potential lmax is the maximum harmonic order nmax is the maximum radial order r is the evaluation radius p will be returned array in harmonics l and radial order n for the potential dp will be returned array in harmonics l and radial order n for the derivative of the potential tid is the thread enumerator that allows the function to provide some thread safety
void Sphere::get_potl(int lmax, int nmax, double r, Eigen::MatrixXd &p, int tid)
Get derivative of potential lmax is the maximum harmonic order nmax is the maximum radial order r is the evaluation radius p will be returned array in harmonics l and radial order n for the potential tid is the thread enumerator that allows the function to provide some thread safety
void Sphere::get_potl_dens(int lmax, int nmax, double r, Eigen::MatrixXd &p, Eigen::MatrixXd &d, int tid)
Get derivative of potential lmax is the maximum harmonic order nmax is the maximum radial order r is the evaluation radius p will be returned array in harmonics l and radial order n for the potential d will be returned array in harmonics l and radial order n for the density tid is the thread enumerator that allows the function to provide some thread safety
void Sphere::initialize(void)
Initialize method.
void Sphere::make_model()
References make_model_bin, make_model_plummer, plummer.
Referenced by determine_coefficients.
void Sphere::make_model_bin()
Referenced by make_model.
void Sphere::make_model_plummer()
Referenced by make_model.
double Sphere::mapDeriv(const std::map< double, double > &data, double x)
double Sphere::mapIntrp(const std::map< double, double > &data, double x)
double Sphere::r_to_xi(double r)
Coordinate mapping.
References ortho.
Referenced by d_r_to_xi.
double Sphere::xi_to_r(double x)
References ortho.
virtual void Sphere::determine_coefficients(void)
Override to redetermine basis, as desired.
References SphericalBasis::determine_coefficients, make_model, recompute, tnext, tnow.
Sphere::Sphere(Component *c0, const YAML::Node &conf, MixtureBasis *m=0)
Constructor c0 is the instantiating caller (Component) conf passes any parameters to basis instance (rsphSL, rmin and numr m allows the spherical basis to be used for multiple center expansions Input line parameters include: rmapping is the radius for coordinate scaling numr is the number of radial grid points cmap set to true for scaling coordinates from the semi-infinite to finite segment diverge set to true means assume a cuspy profile dfac is the power of the "divergent" cusp modelname is the file containing the input background model profile cachename is the name for the SL grid cache file dtime is the interval between basis recomputations (<=0 for never)
virtual Sphere::~Sphere()
Destructor.