SplineSoft
double SplineSoft::eps
double SplineSoft::fac0
Referenced by SplineSoft.
double SplineSoft::fac1
Referenced by SplineSoft.
double SplineSoft::fac2
Referenced by SplineSoft.
double SplineSoft::m1(double x)
Spline kernel integrals.
Referenced by SplineSoft.
double SplineSoft::m2(double x)
Referenced by SplineSoft.
double SplineSoft::p1(double x)
Referenced by SplineSoft.
double SplineSoft::p2(double x)
Referenced by SplineSoft.
std::pair< double, double > SplineSoft::operator()(double r, double eps)
Main operator returning enclosed mass and gravitational potential
SplineSoft::SplineSoft()
Constructor.
References fac0, fac1, fac2, m1, m2, p1, p2.