Component
double Component::mtot0
System mass, center of mass, center of velocity and acceleration.
double * Component::com0
Referenced by ConvertPos, getCenter, Pos, Pos, PosConvert.
double * Component::cov0
Referenced by ConvertVel, Vel, Vel, VelConvert.
double * Component::acc0
Referenced by Acc.
double Component::rcom
Maximum radius for contribution to center-of-mass computation.
double Component::mtot
Total mass.
int Component::dim
Dimension of the phase space.
std::vector< vector<int> > Component::levlist
Particle list per level This will be a sorted list for each level. We use a vector rather than (e.g.) a set for the random insertion
std::vector< vector<unsigned> > Component::mdt_ctr
Multstep dt type counter.
PotAccel* Component::force
Points to associated force instance.
int Component::niattrib
Attribute array dimensions for integer parameters.
int Component::ndattrib
Attribute array dimensions for float-valued parameters.
int Component::EJ
Binding energy orientation flag.
int Component::nEJkeep
Number to keep in orientation stack.
int Component::nEJwant
Target number of particles for average.
int Component::nEJaccel
Target number of states for pseudo-acceleration estimation.
double Component::EJx0
Initial EJ center.
x-coord
double Component::EJy0
y-coord
double Component::EJz0
z-coord
double Component::EJu0
Initial EJ velocity.
x-coord
double Component::EJv0
y-coord
double Component::EJw0
z-coord
double Component::EJdT
Spacing between EJ samples.
bool Component::EJdiag
Print verbose diagnostics.
bool Component::EJdryrun
Do not apply transformation.
bool Component::EJkinE
Use particle KE for energy computation.
bool Component::EJext
Use external potential for energy computation.
bool Component::EJlinear
Move center at constant velocity specified by (EJu0, EJv0, EJw0)
double Component::EJdamp
Damping factor for center determination (< 1.0 for damping)
bool Component::com_system
Use center of mass coordinate system.
Referenced by Acc, ConvertPos, ConvertVel, getCenter, Pos, Pos, PosConvert, Vel, Vel, VelConvert.
bool Component::com_log
Log the center of mass coordinate system at each step.
double Component::rtrunc
Maximum radius from center for force evaluation.
bool Component::timers
CUDA timing info.
Referenced by Cube::exeTimer::~exeTimer.
bool Component::buffered
Use buffered binary writes.
Orient* Component::orient
Orientation cache.
Timer Component::time_so_far
Running clock on the current potential/force evaluation.
Referenced by get_time_sofar.
Component::Component(YAML::Node &conf)
The constructor.
Takes the id string id and phase space file name as arguments
Component::Component(YAML::Node &, istream *in, bool SPL)
Initialize from file.
Component::~Component()
Destructor.
PartPtr * Component::get_particles(int *number)
Parallel gather.
int Component::particle_count(int node)
Retrieve particle count on a particular node (one node at a time)
References nbodies_table, numprocs.
vector< unsigned int > Component::particle_count()
Retrieve particle count on a particular node (all nodes at once)
References nbodies_table.
void Component::write_binary(ostream *out, bool real4=false)
Write binary component phase-space structure.
void Component::write_binary_header(ostream *out, bool real4, std::string prefix, int nth=1)
Write header for per-node writes.
void Component::write_binary_particles(std::ostream *out, bool real4)
Write particles for per-node writes.
void Component::write_binary_particles(std::vector< std::shared_ptr< std::ofstream > > &out, bool real4)
Write particles for per-node writes (multithreaded version)
void Component::write_binary_particles(std::ostream *out, int threads, bool real4)
Write particles for per-node writes with multithreading.
void Component::write_binary_mpi(MPI_File &out, MPI_Offset &offset, bool real4=false)
Write binary component phase-space structure using MPI.
References blocking, write_binary_mpi_b, write_binary_mpi_i.
void Component::write_ascii(ostream *out, bool accel=false)
Write ascii component phase-space structure.
void Component::redistribute_particles(void)
Redestribute this component.
void Component::fix_positions_cpu(unsigned mlevel=0)
Compute center of mass and center of velocity (CPU version)
Referenced by fix_positions.
void Component::fix_positions(unsigned mlevel=0)
Compute center of mass and center of velocity.
References fix_positions_cpu, use_cuda.
void Component::redistributeByList(vector< int > &redist)
Redistribute particle by list (deprecated?) Serialize redistribution list into an integer array of numprocs stanzas, each with the format n current node M number to redistribute (may be zero) index_1 tonode_1 index_2 tonode_2 . . index_M tonode_M so each stanza has 2(M+1) integers
void Component::update_accel(void)
Subtract mean acceleration from each particle accel.
void Component::get_angmom(unsigned mlevel=0)
Update angular momentum values.
double Component::Adiabatic(void)
Adiabatic turn on factor, range in [0, 1].
bool Component::freeze(unsigned indx)
Is particle out of bounds?
bool Component::escape_com(const Particle &)
Is particle beyond COM system.
PartMap & Component::Particles()
Access to particle vector.
References particles.
Particle * Component::Part(unsigned long i)
Access to particle as a pointer.
References particles.
PartPtr Component::partPtr(unsigned long i)
Access to particle via the shared pointer.
References particles.
bool Component::partExists(unsigned long i)
Check if particle index is in the component.
References particles.
Particle * Component::GetNewPart()
Generate new particle: this adds a new particle and returns a pointer to the same particle. It is the caller's responsbility to populate the phase space and particle attributes with sane values.
void Component::AddPart(PartPtr p)
Add a particle to the component.
void Component::DestroyPart(PartPtr p)
Remove a particle from the component.
void Component::ErasePart(PartPtr p)
Erase a particle with no level list check.
References nbodies, particles.
unsigned Component::Number()
Particle vector size.
References particles.
unsigned Component::CurTotal()
Return the last particle total (no MPI)
References nbodies_tot.
unsigned Component::NewTotal()
Update total number of particles in component. Should be called after adding or killing particles. Uses MPI.
References modified, nbodies_tot, seq_new_particles.
double Component::Mass(int i)
Access to mass.
References particles.
double Component::Pos(int i, int j, unsigned flags=Inertial)
Access to positions.
References center, Centered, com0, com_system, Local, particles.
std::vector< double > Component::getCenter(unsigned flags=Inertial)
Get rectified component center.
References center, Centered, com0, com_system, Local.
double Component::Vel(int i, int j, unsigned flags=Inertial)
Access to velocities.
References com_system, cov0, Local, particles.
void Component::Pos(double *pos, int i, unsigned flags=Inertial)
Get positions.
References center, Centered, com0, com_system, Local, particles.
void Component::Vel(double *vel, int i, unsigned flags=Inertial)
Get velocities.
References com_system, cov0, Local, particles.
void Component::ConvertPos(double *pos, unsigned flags=Local|Centered)
Convert coordinates from inertial to local.
References center, Centered, com0, com_system, Inertial, Local.
void Component::ConvertVel(double *vel, unsigned flags=Local|Centered)
Convert velocities from inertial to local.
References com_system, cov0, Inertial, Local.
void Component::PosConvert(double *pos, unsigned flags=Local|Centered)
Convert coordinates from local to inertial.
References center, Centered, com0, com_system, Inertial, Local.
void Component::VelConvert(double *vel, unsigned flags=Local|Centered)
Convert velocities from local inertial.
References com_system, cov0, Inertial, Local.
double Component::Acc(int i, int j, unsigned flags=Inertial)
Access to acceleration.
References acc0, com_system, Inertial, particles.
void Component::AddPos(int i, int j, double val)
Add to position (by component)
References particles.
void Component::AddPos(int i, double *val)
Add to position (by array)
References particles.
void Component::AddPos(int i, vector< double > &val)
Add to position (by vector)
References particles.
void Component::AddVel(int i, int j, double val)
Add to velocity (by component)
References particles.
void Component::AddVel(int i, double *val)
Add to velocity (by array)
References particles.
void Component::AddVel(int i, vector< double > &val)
Add to velocity (by vector)
References particles.
void Component::AddAcc(int i, int j, double val)
Add to accerlation (by component)
References getPseudoAccel, particles.
void Component::AddAccExt(int i, int j, double val)
Add to accerlation (by component)
References particles.
void Component::AddAcc(int i, double *val)
Add to acceleration (by array)
References getPseudoAccel, particles.
void Component::AddAccExt(int i, double *val)
Add to acceleration (by array)
References particles.
void Component::AddAcc(int i, vector< double > &val)
Add to accerlation (by vector)
References getPseudoAccel, particles.
void Component::AddAccExt(int i, vector< double > &val)
Add to accerlation (by vector)
References particles.
void Component::AddPot(int i, double val)
Add to potential.
References particles.
void Component::AddPotExt(int i, double val)
Add to external potential.
References particles.
void Component::reset_level_lists()
Reset the level lists.
void Component::print_level_lists(double T)
Print out the level lists to stdout for diagnostic purposes.
double Component::get_time_sofar()
Time in potential/force computation so far.
References Timer::getTime, time_so_far.
bool Component::Indexing()
Check for indexing.
References indexing.
bool Component::NoSwitch()
Check for multistep restriction (this is still a test option)
References noswitch.
Referenced by Cylinder::multistep_update_begin.
bool Component::FreezeLev()
Only compute new levels on first step.
References freezeLev.
bool Component::DTreset()
Compute level from minimum requested time step from last master step.
References dtreset.
PSTYPE
friend class ComponentContainer
friend class OrbTrace
friend class ScatterMFP
const unsigned long Component::magic
For magic number checking.
const unsigned long Component::mmask
const unsigned long Component::nmask
bool Component::adiabatic
bool Component::aindex
vector<double> Component::angmom_lev
bool Component::blocking
Using blocking writes for MPI-IO.
Referenced by write_binary_mpi.
vector<double> Component::coa_lev
vector<double> Component::com_lev
vector<double> Component::com_mas
vector<double> Component::comE_lev
vector<double> Component::comE_mas
bool Component::consp
vector<double> Component::cov_lev
vector<double> Component::covE_lev
bool Component::indexing
Internal data for sequence checking.
Referenced by Indexing.
vector<loadb_datum> Component::loadb
std::vector<PartPtr> Component::pbuf
int Component::pBufSiz
Particle buffer count for MPI-IO writing.
ParticleFerryPtr Component::pf
unsigned Component::rsize
int Component::seq_beg
int Component::seq_cur
int Component::seq_end
int Component::tidal
double Component::toff
double Component::ton
double Component::twid
bool Component::umagic
double Component::azcm_slab
Slab parameters.
bool Component::binary
Binary read flag.
Component* Component::c0
Use center from this component.
std::shared_ptr<CenterFile> Component::CF
Center file playback.
int Component::com_restart
COM flag.
string Component::comfile
COM log file.
std::string Component::ctr_name
Name of the centering component.
bool Component::dtreset
Select level from criteria over last time step.
Referenced by DTreset.
bool Component::freezeLev
Compute new levels on the first step only.
Referenced by FreezeLev.
unsigned Component::modified
Particle number update is needed.
Referenced by NewTotal.
unsigned int Component::nbodies
Bodies on this node.
Referenced by ErasePart.
vector<unsigned int> Component::nbodies_index
vector<unsigned int> Component::nbodies_table
Vector holding current particle partition.
Referenced by particle_count, particle_count.
unsigned int Component::nbodies_tot
Bodies on all nodes.
Referenced by CurTotal, NewTotal.
std::list<PartPtr> Component::new_particles
Particles waiting for a new index.
int Component::nlevel
Level occupation output.
bool Component::noswitch
No multistep switching.
Referenced by NoSwitch.
vector<double> Component::orates
Vectors for holding the rates per node for load balancing.
PartMap Component::particles
Points to associated particles using sequence number.
Referenced by Acc, AddAcc, AddAcc, AddAcc, AddAccExt, AddAccExt, AddAccExt, AddPos, AddPos, AddPos, AddPot, AddPotExt, AddVel, AddVel, AddVel, ErasePart, Mass, Number, Part, partExists, Particles, partPtr, Pos, Pos, Vel, Vel.
MPI_Datatype Component::Particletype
Used by gather and distribution routines to define a particle structure to MPI
unsigned long Component::top_seq
Maximum sequence value so far.
vector<double> Component::trates
const std::set<std::string> Component::valid_keys_force
const std::set<std::string> Component::valid_keys_parm
const std::set<std::string> Component::valid_keys_top
Valid keys for YAML configurations.
Eigen::Vector3d Component::accel
Pseudo-accleration (set by Orient)
double* Component::angmom
Angular momentum vector.
YAML::Node Component::cconf
Parameters for component.
double* Component::center
Center (e.g. set by Orient)
Referenced by ConvertPos, getCenter, Pos, Pos, PosConvert.
double* Component::coa
Center of acceleration.
double* Component::com
Center of mass.
These are pointers to the center of mass, center of velocity, angular momentum and the phase-space 6 vector.
YAML::Node Component::conf
Configuration for this component.
double* Component::cov
Center of velocity.
bool Component::cube
Periodic cube.
bool Component::disk
Cylindrical geometry.
Eigen::Vector3d Component::domdt
YAML::Node Component::fconf
Parameters for force.
std::string Component::id
Force method.
int Component::keyPos
Species key position in particle integer attribute vector.
std::string Component::name
Identify this component.
Referenced by Cube::exeTimer::~exeTimer.
Eigen::Vector3d Component::omega
std::string Component::pfile
Particle file.
bool Component::point_mass
Point masses.
double* Component::ps
Phase space vector.
Eigen::Vector3d Component::pseudo
double Component::rmax
Maximum initial particle radius.
bool Component::slab
Slab geometry.
bool Component::sphere
Spherical geometry.
void Component::add_particles(int from, int to, std::vector< PartPtr > &plist)
void Component::initialize_com_system()
void Component::load_balance(void)
Parallel distribute and particle io.
void Component::openNextBlob(std::ifstream &in, std::list< std::string >::iterator &fit, int &N)
Helper for split-PSP-file particle consumer.
void Component::read_bodies_and_distribute_ascii(void)
void Component::read_bodies_and_distribute_binary_out(istream *)
void Component::read_bodies_and_distribute_binary_spl(istream *)
int Component::round_up(double dnumb)
void Component::update_indices(void)
void Component::configure(void)
Set configuration and force.
void Component::find_ctr_component()
Locagte centering component.
void Component::initialize(void)
Initialize parameters (called by ComponentContainer after component instantiation
void Component::initialize_cuda(void)
Enumerate and initialize cuda devices.
void Component::restart_com_system(void)
COM restart function.
void Component::seq_new_particles()
Update sequence number of added particles.
Referenced by NewTotal.
void Component::set_default_values()
Set default, unset parameters in config.
void Component::setup_distribution(void)
Setup distribution vectors.
void Component::write_binary_mpi_b(MPI_File &out, MPI_Offset &offset, bool real4=false)
Write binary component phase-space structure using MPI (blocking)
Referenced by write_binary_mpi.
void Component::write_binary_mpi_i(MPI_File &out, MPI_Offset &offset, bool real4=false)
Write binary component phase-space structure using MPI (non-blocking)
Referenced by write_binary_mpi.
Eigen::Vector3d & Component::getPseudoAccel(double *pos, double *vel)
Referenced by AddAcc, AddAcc, AddAcc.