EXPException
bool EXPException::deadlock
Possible deadlock?
Referenced by EXPException, EXPException, getDeadlock.
int EXPException::errorcode
Return code.
Referenced by EXPException, EXPException, getErrorcode.
std::string EXPException::errormessage
Error message describing the error in more detail.
Referenced by BadIndexException::BadIndexException, EXPException, FileCreateError::FileCreateError, FileCreateError::FileCreateError, FileOpenError::FileOpenError, FileOpenError::FileOpenError, GenericError::GenericError, getErrorMessage, InternalError::InternalError, InternalError::InternalError, YamlConfigError::YamlConfigError.
std::string EXPException::exceptionname
Friendly name of the exception.
Referenced by BadIndexException::BadIndexException, EXPException, FileCreateError::FileCreateError, FileCreateError::FileCreateError, FileOpenError::FileOpenError, FileOpenError::FileOpenError, GenericError::GenericError, getErrorMessage, InternalError::InternalError, InternalError::InternalError, YamlConfigError::YamlConfigError.
std::string EXPException::msg_
Message buffer.
Referenced by BadIndexException::BadIndexException, EXPException, EXPException, FileCreateError::FileCreateError, FileCreateError::FileCreateError, FileOpenError::FileOpenError, FileOpenError::FileOpenError, GenericError::GenericError, InternalError::InternalError, InternalError::InternalError, what, YamlConfigError::YamlConfigError.
std::string EXPException::sourcefilename
Source file where throw occured.
Referenced by EXPException, EXPException, getErrorMessage.
int EXPException::sourcelinenumber
Line number of throw.
Referenced by EXPException, EXPException, getErrorMessage.
EXPException::EXPException(const std::string exceptionname, const std::string message, const std::string sourcefilename, int sourcelinenumber, int errorcode=-1, bool deadlock=false)
Constructor for base exceptionname Human-readable identifier for the error message Error details for the user sourcefilename File where the thrower resides sourcelinenumber Line number in the source for the thrower errorcode Error code to report at top-level catch deadlock Exception may break MPI synchronization
References deadlock, errorcode, errormessage, exceptionname, getErrorMessage, msg_, sourcefilename, sourcelinenumber.
bool EXPException::getDeadlock()
Get deadlock status.
References deadlock.
int EXPException::getErrorcode()
Get errorcode.
References errorcode.
std::string EXPException::getErrorMessage()
Returns an error message suitable for printing to the user. Also called by derived classes to assemble the error message for std::exception::what()
References errormessage, exceptionname, sourcefilename, sourcelinenumber.
Referenced by BadIndexException::BadIndexException, EXPException, EXPException, FileCreateError::FileCreateError, FileCreateError::FileCreateError, FileOpenError::FileOpenError, FileOpenError::FileOpenError, GenericError::GenericError, InternalError::InternalError, InternalError::InternalError, YamlConfigError::YamlConfigError.
virtual const char * EXPException::what() const
std::exception member returns a pointer to the error message A pointer to a const char*. The std::string "buffer" used for assembling and passing the message to std::exception will be deleted when the exception is deleted.
References msg_.
virtual EXPException::~EXPException()
Destructor for base. Virtual to permit derived classes.
EXPException::EXPException(const std::string sourcefile, int linenumber, int errorcode=-1, bool deadlock=false)
Protected so it is only called by properly implemented classes.
References deadlock, errorcode, getErrorMessage, msg_, sourcefilename, sourcelinenumber.