point
std::array<coordinate_type, dimensions> point< coordinate_type, dimensions >::coords_
Referenced by point< coordinate_type, dimensions >::get, point< coordinate_type, dimensions >::point, point< coordinate_type, dimensions >::point, point< coordinate_type, dimensions >::point.
unsigned long point< coordinate_type, dimensions >::indx_
Referenced by point< coordinate_type, dimensions >::indx, point< coordinate_type, dimensions >::point.
double point< coordinate_type, dimensions >::mass_
Referenced by point< coordinate_type, dimensions >::mass, point< coordinate_type, dimensions >::point.
std::array<coordinate_type, dimensions> point< coordinate_type, dimensions >::vels_
Referenced by point< coordinate_type, dimensions >::point, point< coordinate_type, dimensions >::point, point< coordinate_type, dimensions >::vel.
double point< coordinate_type, dimensions >::distance(const point &pt) const
Returns the distance squared from this point to another point. pt another point distance squared from this point to the other point
References point< coordinate_type, dimensions >::get.
Referenced by kdtree< coordinate_type, dimensions >::node::distance.
coordinate_type point< coordinate_type, dimensions >::get(size_t index) const
Returns the coordinate in the given dimension. index dimension index (zero based) coordinate in the given dimension
References point< coordinate_type, dimensions >::coords_.
Referenced by point< coordinate_type, dimensions >::distance, kdtree< coordinate_type, dimensions >::node::get, kdtree< coordinate_type, dimensions >::nearestN, kdtree< coordinate_type, dimensions >::node_cmp::operator(), operator<<.
unsigned long point< coordinate_type, dimensions >::indx() const
References point< coordinate_type, dimensions >::indx_.
double point< coordinate_type, dimensions >::mass() const
References point< coordinate_type, dimensions >::mass_.
point< coordinate_type, dimensions >::point()
Null initializer.
point< coordinate_type, dimensions >::point(const point &p)
Copy constructor.
References point< coordinate_type, dimensions >::coords_, point< coordinate_type, dimensions >::indx_, point< coordinate_type, dimensions >::mass_, point< coordinate_type, dimensions >::vels_.
point< coordinate_type, dimensions >::point(std::array< coordinate_type, dimensions > c, double m=1, unsigned long indx=0)
Constructor.
point< coordinate_type, dimensions >::point(std::array< coordinate_type, dimensions > c, std::array< coordinate_type, dimensions > v, double m=1, unsigned long indx=0)
point< coordinate_type, dimensions >::point(std::initializer_list< coordinate_type > list, double m=1, unsigned long indx=0)
List constructor.
References point< coordinate_type, dimensions >::coords_.
point< coordinate_type, dimensions >::point(std::initializer_list< coordinate_type > list, std::initializer_list< coordinate_type > vlst, double m=1, unsigned long indx=0)
References point< coordinate_type, dimensions >::coords_, point< coordinate_type, dimensions >::vels_.
double point< coordinate_type, dimensions >::speed(const point &pt) const
Returns the squared velocity between this point to another point. pt another point squared speed between this point and the other point
References point< coordinate_type, dimensions >::vel.
coordinate_type point< coordinate_type, dimensions >::vel(size_t index) const
References point< coordinate_type, dimensions >::vels_.
Referenced by point< coordinate_type, dimensions >::speed.