HQSphere
double HQSphere::rbmax
Referenced by rb_max.
double HQSphere::rbmin
Referenced by rb_min.
double HQSphere::d_r_to_rb(double const)
void HQSphere::dens(const int nn, const int l, const double r, Eigen::VectorXd &a)
double HQSphere::dens(const int nn, const int l, const double rb)
Referenced by densR.
double HQSphere::densR(const int nn, const int l, const double r)
References dens, r_to_rb.
HQSphere::HQSphere(void)
double HQSphere::krnl(const int nn, const int l)
double HQSphere::norm(const int nn, const int l)
void HQSphere::potl(const int nn, const int l, const double r, Eigen::VectorXd &a)
double HQSphere::potl(const int nn, const int l, const double rb)
Referenced by potlR, potlRZ.
double HQSphere::potlR(const int nn, const int l, const double r)
References potl, r_to_rb.
double HQSphere::potlRZ(const int nn, const int l, const double r, const double z)
References potl, r_to_rb.
double HQSphere::r_to_rb(double const)
Referenced by densR, potlR, potlRZ.
double HQSphere::rb_max(void)
References rbmax.
double HQSphere::rb_min(void)
References rbmin.
double HQSphere::rb_to_r(double const)
virtual HQSphere::~HQSphere()