circular_buffer
typedef const T* circular_buffer< T >::const_pointer
typedef const T& circular_buffer< T >::const_reference
typedef ptrdiff_t circular_buffer< T >::difference_type
typedef T* circular_buffer< T >::pointer
typedef T& circular_buffer< T >::reference
typedef size_t circular_buffer< T >::size_type
typedef T circular_buffer< T >::value_type
typedef BufferIterator<true> circular_buffer< T >::const_iterator
typedef BufferIterator<false> circular_buffer< T >::iterator
circular_buffer< T >::reference circular_buffer< T >::at(size_type index)
circular_buffer< T >::const_reference circular_buffer< T >::at(size_type index) const
circular_buffer< T >::reference circular_buffer< T >::back()
References circular_buffer< T >::empty.
circular_buffer< T >::const_reference circular_buffer< T >::back() const
References circular_buffer< T >::empty.
circular_buffer< T >::iterator circular_buffer< T >::begin()
circular_buffer< T >::const_iterator circular_buffer< T >::begin() const
size_type circular_buffer< T >::buffer_size() const
circular_buffer< T >::size_type circular_buffer< T >::capacity() const
circular_buffer< T >::const_iterator circular_buffer< T >::cbegin() const noexcept
circular_buffer< T >::const_iterator circular_buffer< T >::cend() const noexcept
circular_buffer< T >::circular_buffer(circular_buffer &&other) noexcept
circular_buffer< T >::circular_buffer(const circular_buffer &other)
Copy constructor.
References circular_buffer< T >::data.
circular_buffer< T >::circular_buffer(size_t size)
Constructor.
void circular_buffer< T >::clear()
const_pointer circular_buffer< T >::data() const
Referenced by circular_buffer< T >::circular_buffer, circular_buffer< T >::operator=, circular_buffer< T >::push_back, circular_buffer< T >::push_back.
bool circular_buffer< T >::empty() const
Referenced by circular_buffer< T >::back, circular_buffer< T >::back, circular_buffer< T >::front, circular_buffer< T >::front, circular_buffer< T >::pop_front.
circular_buffer< T >::iterator circular_buffer< T >::end()
circular_buffer< T >::const_iterator circular_buffer< T >::end() const
circular_buffer< T >::reference circular_buffer< T >::front()
References circular_buffer< T >::empty.
circular_buffer< T >::const_reference circular_buffer< T >::front() const
References circular_buffer< T >::empty.
bool circular_buffer< T >::full() const
circular_buffer & circular_buffer< T >::operator=(circular_buffer &&other) noexcept
circular_buffer & circular_buffer< T >::operator=(const circular_buffer &other)
Assignment operator.
References circular_buffer< T >::data.
circular_buffer< T >::reference circular_buffer< T >::operator[](size_type index)
circular_buffer< T >::const_reference circular_buffer< T >::operator[](size_type index) const
void circular_buffer< T >::pop_front()
References circular_buffer< T >::empty.
void circular_buffer< T >::push_back(const value_type &data)
References circular_buffer< T >::data.
void circular_buffer< T >::push_back(value_type &&data) noexcept
References circular_buffer< T >::data.
circular_buffer< T >::const_iterator circular_buffer< T >::rbegin() const noexcept
circular_buffer< T >::iterator circular_buffer< T >::rbegin() noexcept
circular_buffer< T >::const_iterator circular_buffer< T >::rend() const noexcept
circular_buffer< T >::iterator circular_buffer< T >::rend() noexcept
circular_buffer< T >::size_type circular_buffer< T >::size() const