TipsyReader::TipsyNative
std::ifstream TipsyReader::TipsyNative::input
The input file stream.
Referenced by native_header, native_init, read_dark, read_gas, read_star.
friend class PR::Tipsy
int TipsyReader::TipsyNative::native_header()
Read the header.
References TipsyReader::TipsyFile::header, input.
Referenced by native_init.
int TipsyReader::TipsyNative::native_init(const std::string &filename)
References TipsyReader::TipsyFile::header, input, native_header, TipsyReader::Header::nbodies.
Referenced by TipsyNative.
int TipsyReader::TipsyNative::native_read()
References TipsyReader::TipsyFile::dark_particles, TipsyReader::TipsyFile::gas_particles, TipsyReader::TipsyFile::header, TipsyReader::Header::ndark, TipsyReader::Header::nsph, TipsyReader::Header::nstar, read_dark, read_gas, read_star, TipsyReader::TipsyFile::star_particles.
Referenced by readParticles.
void TipsyReader::TipsyNative::read_dark()
References TipsyReader::TipsyFile::dark_particles, TipsyReader::TipsyFile::header, input, TipsyReader::Header::ndark.
Referenced by native_read.
void TipsyReader::TipsyNative::read_gas()
References TipsyReader::TipsyFile::gas_particles, TipsyReader::TipsyFile::header, input, TipsyReader::Header::nsph.
Referenced by native_read.
void TipsyReader::TipsyNative::read_star()
References TipsyReader::TipsyFile::header, input, TipsyReader::Header::nstar, TipsyReader::TipsyFile::star_particles.
Referenced by native_read.
int TipsyReader::TipsyNative::readParticles()
References native_read.
TipsyReader::TipsyNative::TipsyNative(const std::string filename)
References native_init.
TipsyReader::TipsyNative::~TipsyNative()