BSSphere
std::vector<Eigen::VectorXd> BSSphere::a
int BSSphere::lmax
int BSSphere::nmax
double BSSphere::rmax
Referenced by rb_max.
Eigen::VectorXd BSSphere::t_dr
Eigen::MatrixXd BSSphere::t_f
Eigen::MatrixXd BSSphere::t_g
int BSSphere::t_n
Eigen::MatrixXd BSSphere::t_y
void BSSphere::setup_potl_table(void)
BSSphere::BSSphere(double RMAX=1.0, int NMAX=10, int LMAX=10)
double BSSphere::d_r_to_rb(double const r)
void BSSphere::dens(const int nn, const int l, const double r, Eigen::VectorXd &t)
double BSSphere::dens(const int nn, const int l, const double rb)
Referenced by densR.
double BSSphere::densR(const int nn, const int l, const double r)
References dens.
double BSSphere::krnl(const int nn, const int l)
double BSSphere::norm(const int nn, const int l)
void BSSphere::potl(const int nn, const int l, const double r, Eigen::VectorXd &t)
double BSSphere::potl(const int nn, const int l, const double rb)
Referenced by potlR, potlRZ.
double BSSphere::potlR(const int nn, const int l, const double r)
References potl.
double BSSphere::potlRZ(const int nn, const int l, const double r, const double z)
References potl, r_to_rb.
double BSSphere::r_to_rb(double const r)
Referenced by potlRZ.
double BSSphere::rb_max(void)
References rmax.
double BSSphere::rb_min(void)
double BSSphere::rb_to_r(double const r)
virtual BSSphere::~BSSphere()