TwoCenter
typedef double(TwoCenter::* TwoCenter::mixFunc) (double *p))(double *p)
The mixture function.
string TwoCenter::basis
The name of the basis (for reflection)
Basis* TwoCenter::exp_in
Referenced by multistep_debug, multistep_reset, multistep_update, multistep_update_begin, multistep_update_finish, RegisterComponent, set_multistep_level.
Basis* TwoCenter::exp_out
Referenced by multistep_debug, multistep_reset, multistep_update, multistep_update_begin, multistep_update_finish, RegisterComponent, set_multistep_level.
MixtureBasis* TwoCenter::mix_in
Mixture containers for each basis.
MixtureBasis * TwoCenter::mix_out
double TwoCenter::dz
The bin spacing.
vector<double> TwoCenter::histo
The histogram bins.
unsigned TwoCenter::nhisto
Number of bins.
string TwoCenter::ohisto
Name for the histogram file.
const std::set<std::string> TwoCenter::valid_keys
Valid keys for YAML configurations.
vector<double> TwoCenter::inner
INNER center for current component.
vector<double> TwoCenter::outer
OUTER center for current component.
void * TwoCenter::determine_acceleration_and_potential_thread(void *arg)
Multithreading implementation of the force computation.
void * TwoCenter::determine_coefficients_thread(void *arg)
The required force members, but this class does not multithread directly.
void TwoCenter::initialize(void)
Force initialization.
void TwoCenter::reset_histo()
Zero out the histogram bins.
void TwoCenter::write_histo()
Write the current histogram to the log file.
void TwoCenter::accum_histo(double value)
Make a histogram for debugging the mixture factor distribution.
double TwoCenter::Cmixture(double *p)
The complement of the mixture function, also in [0,1].
References mixture.
void TwoCenter::determine_coefficients(Component *c)
Call Basis routines to make coefficients.
void TwoCenter::determine_coefficients(void)
Used by get_acceleration_and_potential to request that the expansion be performed.
void TwoCenter::get_acceleration_and_potential(Component *)
Main force evaluation routine: cycle through each grid.
virtual double TwoCenter::mixture(double *p)=0
Mixture function for the two expansions.
To be provided: must return a value in [0,1]
Referenced by Cmixture.
virtual void TwoCenter::multistep_debug()
Print debug info.
References exp_in, exp_out, multistep_debug.
Referenced by multistep_debug.
virtual void TwoCenter::multistep_reset()
Reset data for multistep.
References exp_in, exp_out, multistep_reset.
Referenced by multistep_reset.
virtual void TwoCenter::multistep_update(int cur, int next, Component *c, int i, int id)
Implementation of level shifts.
References exp_in, exp_out, multistep_update.
Referenced by multistep_update.
virtual void TwoCenter::multistep_update_begin()
Execute to begin level shifts for particles.
Update the multi time step force algorithm when moving particle i from level cur to level next
References exp_in, exp_out, multistep_update_begin.
Referenced by multistep_update_begin.
virtual void TwoCenter::multistep_update_finish()
Execute to finish level shifts for particles.
References exp_in, exp_out, multistep_update_finish.
Referenced by multistep_update_finish.
virtual void TwoCenter::RegisterComponent(Component *c)
For access to parent component.
References PotAccel::component, exp_in, exp_out, RegisterComponent.
Referenced by RegisterComponent.
virtual void TwoCenter::set_multistep_level(unsigned n)
Multistepping routines: call the basis members for each component.
References exp_in, exp_out, PotAccel::mlevel, set_multistep_level.
Referenced by set_multistep_level.
TwoCenter::TwoCenter(Component *c0, const YAML::Node &conf)
Constructor c0 is the instantiating caller (a Component) line passes any parameters (rsphSL, rmin and numr)
TwoCenter::~TwoCenter()
Destructor.