RunningTime
double RunningTime::accum
Referenced by append, initialize, lap.
std::deque<double> RunningTime::boxcar
Referenced by append.
double RunningTime::current
Referenced by append, getTavg, initialize.
double RunningTime::last
Referenced by append, getLast, lap.
unsigned RunningTime::nkeep
Referenced by append, initialize.
Timer RunningTime::timer
Referenced by append, lap, Start, Stop.
double RunningTime::value
Referenced by append, getTime, initialize.
void RunningTime::append()
References accum, boxcar, current, Timer::getTime, last, nkeep, timer, value.
Referenced by Stop.
void RunningTime::initialize(unsigned n)
References accum, current, nkeep, value.
Referenced by RunningTime, RunningTime.
void RunningTime::lap()
References accum, Timer::getTime, last, timer.
Referenced by Stop.
double RunningTime::getLast()
References last.
double RunningTime::getTavg()
References current.
double RunningTime::getTime()
References value.
RunningTime::RunningTime()
References initialize.
RunningTime::RunningTime(unsigned n)
References initialize.
void RunningTime::Start()
References Timer::start, timer.
void RunningTime::Stop(bool final=true)
References append, lap, Timer::reset, Timer::stop, timer.