EnumBitset
std::bitset<static_cast<typename std::underlying_type<T>::type>(EnumTraits<T>::max)> EnumBitset< T >::s
The underlying bitset.
Referenced by EnumBitset< T >::flip, EnumBitset< T >::operator[], EnumBitset< T >::operator[], EnumBitset< T >::reset, EnumBitset< T >::reset, EnumBitset< T >::set, EnumBitset< T >::size, EnumBitset< T >::test.
std::underlying_type< T >::type EnumBitset< T >::get_value(T v) const
Referenced by EnumBitset< T >::flip, EnumBitset< T >::operator[], EnumBitset< T >::reset, EnumBitset< T >::set, EnumBitset< T >::test.
EnumBitset< T >::EnumBitset()
Constructor.
EnumBitset & EnumBitset< T >::flip(T pos)
Flip the flag.
References EnumBitset< T >::flip, EnumBitset< T >::get_value, EnumBitset< T >::s.
Referenced by EnumBitset< T >::flip.
bool EnumBitset< T >::operator[](size_t i) const
operator version of the test
References EnumBitset< T >::s.
bool EnumBitset< T >::operator[](T pos) const
operator version of the test
References EnumBitset< T >::get_value, EnumBitset< T >::s.
void EnumBitset< T >::reset()
Reset all flags.
References EnumBitset< T >::s.
EnumBitset & EnumBitset< T >::reset(T pos)
Reset the flag.
References EnumBitset< T >::get_value, EnumBitset< T >::reset, EnumBitset< T >::s.
Referenced by EnumBitset< T >::reset.
EnumBitset & EnumBitset< T >::set(T pos)
Set the flag.
References EnumBitset< T >::get_value, EnumBitset< T >::s, EnumBitset< T >::set.
Referenced by EnumBitset< T >::set.
size_t EnumBitset< T >::size()
Return size of bitset.
References EnumBitset< T >::s.
bool EnumBitset< T >::test(T pos) const
Test the flag.
References EnumBitset< T >::get_value, EnumBitset< T >::s.