BiorthCyl
double BiorthCyl::acylcut
double BiorthCyl::acyltbl
std::string BiorthCyl::biorth
std::string BiorthCyl::cachename
Active cache file name.
int BiorthCyl::cmapR
Grid parameters.
int BiorthCyl::cmapZ
YAML::Node BiorthCyl::conf
std::vector<std::vector<Eigen::MatrixXd> > BiorthCyl::dens
Storage for basis arrays.
Referenced by get_dens, get_dens.
YAML::Node BiorthCyl::diskconf
std::string BiorthCyl::disktype
Density target name.
double BiorthCyl::dx
double BiorthCyl::dy
EmpCyl2d BiorthCyl::emp
The 2d basis instance.
Referenced by getBiorthName, getModelName.
bool BiorthCyl::EVEN_M
std::string BiorthCyl::forceID
std::string BiorthCyl::geometry
int BiorthCyl::knots
bool BiorthCyl::logr
int BiorthCyl::mlim
int BiorthCyl::mmax
int BiorthCyl::mmin
double BiorthCyl::Mouter
double BiorthCyl::Ninner
int BiorthCyl::nlim
int BiorthCyl::nmax
int BiorthCyl::nmaxfid
int BiorthCyl::nmin
int BiorthCyl::NQDHT
int BiorthCyl::numr
int BiorthCyl::numx
int BiorthCyl::numy
std::vector<std::vector<Eigen::MatrixXd> > BiorthCyl::pot
Referenced by get_pot, get_pot.
double BiorthCyl::rcylmax
Referenced by getRtable.
double BiorthCyl::rcylmin
std::vector<std::vector<Eigen::MatrixXd> > BiorthCyl::rforce
Referenced by get_rforce, get_rforce.
double BiorthCyl::scale
Referenced by getRtable.
bool BiorthCyl::use_mpi
bool BiorthCyl::verbose
double BiorthCyl::xmax
Referenced by getXmax.
double BiorthCyl::xmin
Referenced by getXmin.
double BiorthCyl::ymax
Referenced by getYmax.
double BiorthCyl::ymin
Referenced by getYmin.
std::vector<std::vector<Eigen::MatrixXd> > BiorthCyl::zforce
Referenced by get_zforce, get_zforce.
std::string BiorthCyl::Version
Cache versioning.
int BiorthCyl::mpi
Flag for MPI enabled (default: 0=off)
void BiorthCyl::create_tables()
Build basis tables.
void BiorthCyl::initialize()
Create storage arrays.
void BiorthCyl::interp(double R, double z, const std::vector< std::vector< Eigen::MatrixXd > > &mat, Eigen::MatrixXd &ret, bool anti_symmetric=false)
Matrix interpolation on grid for coefficient composition.
double BiorthCyl::interp(int m, int n, double R, double z, const std::vector< std::vector< Eigen::MatrixXd > > &mat, bool anti_symmetric=false)
Interpolate on grid.
Referenced by get_dens, get_dens, get_pot, get_pot, get_rforce, get_rforce, get_zforce, get_zforce.
virtual void BiorthCyl::ReadH5Arrays(HighFive::Group &arrays)
Read the basis arrays.
virtual bool BiorthCyl::ReadH5Cache()
Read the HDF5 cache.
virtual void BiorthCyl::WriteH5Arrays(HighFive::Group &arrays)
Write the basis arrays.
virtual void BiorthCyl::WriteH5Cache()
Write the HDF5 cache.
virtual void BiorthCyl::WriteH5Params(HighFive::File &file)
Write parameter attributes (needed for derived classes)
BiorthCyl::BiorthCyl(const YAML::Node &conf)
Constructor.
double BiorthCyl::d_xi_to_r(double x)
Jacobian of nondimensional radial coordinate mapping.
double BiorthCyl::d_yi_to_z(double y)
Jacobian of nondimensional vertical coordinate mapping.
void BiorthCyl::dump_basis(const string &name)
Dump the basis for plotting.
double BiorthCyl::get_dens(double x, double y, int m, int n)
Get density for dimensionless coord with harmonic order l and radial orer n
References dens, interp, xi_to_r, yi_to_z.
void BiorthCyl::get_dens(Eigen::MatrixXd &d, double r, double z)
Get density for dimensionless coord with harmonic order l and radial orer n
References dens, interp.
double BiorthCyl::get_pot(double x, double y, int m, int n)
Get potential for dimensionless coord with harmonic order m and radial orer n.
References interp, pot, xi_to_r, yi_to_z.
void BiorthCyl::get_pot(Eigen::MatrixXd &p, double r, double z)
Get potential for dimensionless coord with harmonic order m and radial orer n.
References interp, pot.
void BiorthCyl::get_pot(Eigen::MatrixXd &Vc, Eigen::MatrixXd &Vs, double r, double z)
Evaluate all orders in matrices; for n-body.
double BiorthCyl::get_rforce(double x, double y, int m, int n)
Get radial force for dimensionless coord with harmonic order l and radial orer n.
References interp, rforce, xi_to_r, yi_to_z.
void BiorthCyl::get_rforce(Eigen::MatrixXd &f, double r, double z)
Get radial force for dimensionless coord with harmonic order l and radial orer n.
References interp, rforce.
double BiorthCyl::get_zforce(double x, double y, int m, int n)
Get radial force for dimensionless coord with harmonic order l and radial orer n.
References interp, xi_to_r, yi_to_z, zforce.
void BiorthCyl::get_zforce(Eigen::MatrixXd &f, double r, double z)
Get radial force for dimensionless coord with harmonic order l and radial orer n.
References interp, zforce.
const std::string BiorthCyl::getBiorthName()
Get biorthogonal function base name.
References emp, EmpCyl2d::getBiorthName.
const std::string BiorthCyl::getModelName()
Get model name.
References emp, EmpCyl2d::getModelName.
double BiorthCyl::getRtable()
Get the table bounds.
References rcylmax, scale.
double BiorthCyl::getXmax()
References xmax.
double BiorthCyl::getXmin()
Get table range bounds.
References xmin.
double BiorthCyl::getYmax()
References ymax.
double BiorthCyl::getYmin()
References ymin.
std::vector< Eigen::MatrixXd > BiorthCyl::orthoCheck()
For pyEXP.
double BiorthCyl::r_to_xi(double r)
Map radial coordinate to nondimensional coordinate.
double BiorthCyl::xi_to_r(double x)
Map nondimensional coordinate to radial coordinate.
Referenced by get_dens, get_pot, get_rforce, get_zforce.
double BiorthCyl::yi_to_z(double y)
Map of nondimensional coordinate to vertical coordinate.
Referenced by get_dens, get_pot, get_rforce, get_zforce.
double BiorthCyl::z_to_yi(double z)
Map of vertical coordinate to nondimesional coordinate.
virtual BiorthCyl::~BiorthCyl()
Destructor.
static std::map< std::string, std::string > BiorthCyl::cacheInfo(const std::string &cachefile, bool verbose=true)
Read and print the cache and return the header parameters as a map/dictionary
static YAML::Node BiorthCyl::getHeader(const std::string &cachefile)
Read the cache and report parameters.