kdtree
typedef point<coordinate_type, dimensions> kdtree< coordinate_type, dimensions >::point_type
Cache<double, node*> kdtree< coordinate_type, dimensions >::best_
Referenced by kdtree< coordinate_type, dimensions >::distance, kdtree< coordinate_type, dimensions >::getDist, kdtree< coordinate_type, dimensions >::kdtree, kdtree< coordinate_type, dimensions >::kdtree, kdtree< coordinate_type, dimensions >::nearestList, kdtree< coordinate_type, dimensions >::nearestN, kdtree< coordinate_type, dimensions >::nearestN.
std::vector<node> kdtree< coordinate_type, dimensions >::nodes_
Referenced by kdtree< coordinate_type, dimensions >::empty, kdtree< coordinate_type, dimensions >::kdtree, kdtree< coordinate_type, dimensions >::kdtree, kdtree< coordinate_type, dimensions >::make_tree.
node* kdtree< coordinate_type, dimensions >::root_
Referenced by kdtree< coordinate_type, dimensions >::kdtree, kdtree< coordinate_type, dimensions >::kdtree, kdtree< coordinate_type, dimensions >::nearestList, kdtree< coordinate_type, dimensions >::nearestN.
size_t kdtree< coordinate_type, dimensions >::visited_
Referenced by kdtree< coordinate_type, dimensions >::kdtree, kdtree< coordinate_type, dimensions >::kdtree, kdtree< coordinate_type, dimensions >::nearestList, kdtree< coordinate_type, dimensions >::nearestN, kdtree< coordinate_type, dimensions >::nearestN, kdtree< coordinate_type, dimensions >::visited.
node * kdtree< coordinate_type, dimensions >::make_tree(size_t begin, size_t end, size_t index)
References kdtree< coordinate_type, dimensions >::make_tree, kdtree< coordinate_type, dimensions >::nodes_.
Referenced by kdtree< coordinate_type, dimensions >::kdtree, kdtree< coordinate_type, dimensions >::kdtree, kdtree< coordinate_type, dimensions >::make_tree.
void kdtree< coordinate_type, dimensions >::nearestN(node *root, const point_type &point, size_t index, int N)
References kdtree< coordinate_type, dimensions >::best_, kdtree< coordinate_type, dimensions >::node::distance, point< coordinate_type, dimensions >::get, kdtree< coordinate_type, dimensions >::node::get, kdtree< coordinate_type, dimensions >::node::left_, kdtree< coordinate_type, dimensions >::nearestN, kdtree< coordinate_type, dimensions >::node::right_, kdtree< coordinate_type, dimensions >::visited_.
Referenced by kdtree< coordinate_type, dimensions >::nearestList, kdtree< coordinate_type, dimensions >::nearestN, kdtree< coordinate_type, dimensions >::nearestN.
double kdtree< coordinate_type, dimensions >::distance() const
Returns the distance between the input point and return value from the last call to nearest().
References kdtree< coordinate_type, dimensions >::best_.
bool kdtree< coordinate_type, dimensions >::empty() const
Returns true if the tree is empty, false otherwise.
References kdtree< coordinate_type, dimensions >::nodes_.
std::vector< double > kdtree< coordinate_type, dimensions >::getDist()
References kdtree< coordinate_type, dimensions >::best_.
kdtree< coordinate_type, dimensions >::kdtree(const kdtree &)=delete
Copy constructor2.
kdtree< coordinate_type, dimensions >::kdtree(func &&f, size_t n)
Constructor taking a function object that generates points. The function object will be called n times to populate the tree. f function that returns a point n number of points to add
References kdtree< coordinate_type, dimensions >::best_, kdtree< coordinate_type, dimensions >::make_tree, kdtree< coordinate_type, dimensions >::nodes_, kdtree< coordinate_type, dimensions >::root_, kdtree< coordinate_type, dimensions >::visited_.
kdtree< coordinate_type, dimensions >::kdtree(iterator begin, iterator end)
Constructor taking a pair of iterators. Adds each point in the range [begin, end) to the tree. begin start of range end end of range
References kdtree< coordinate_type, dimensions >::best_, kdtree< coordinate_type, dimensions >::make_tree, kdtree< coordinate_type, dimensions >::nodes_, kdtree< coordinate_type, dimensions >::root_, kdtree< coordinate_type, dimensions >::visited_.
std::tuple< std::vector< point_type >, double > kdtree< coordinate_type, dimensions >::nearestList(const point_type &pt, int N)
Finds the nearest N points in the tree to the given point. It is not valid to call this function if the tree is empty. pt a point N is the number of nearest points Returns: tuple of the nearest point list and the radius of the Nth point
References kdtree< coordinate_type, dimensions >::best_, kdtree< coordinate_type, dimensions >::nearestN, kdtree< coordinate_type, dimensions >::root_, kdtree< coordinate_type, dimensions >::visited_.
std::tuple< point_type, double, double > kdtree< coordinate_type, dimensions >::nearestN(const point_type &pt, int N)
Finds the nearest N points in the tree to the given point. It is not valid to call this function if the tree is empty. pt a point N is the number of nearest points Returns: tuple of the first points, summed weight, and the radius of the Nth point
References kdtree< coordinate_type, dimensions >::best_, kdtree< coordinate_type, dimensions >::nearestN, kdtree< coordinate_type, dimensions >::root_, kdtree< coordinate_type, dimensions >::visited_.
kdtree & kdtree< coordinate_type, dimensions >::operator=(const kdtree &)=delete
size_t kdtree< coordinate_type, dimensions >::visited() const
Returns the number of nodes visited by the last call to nearest().
References kdtree< coordinate_type, dimensions >::visited_.