OneDModel
bool OneDModel::dist_defined
Referenced by Sech2::Sech2, Sech2::Sech2, Sech2Halo::Sech2Halo, Sech2mu::Sech2mu, Sech2mu::Sech2mu, Sech2mu::setMu.
virtual double OneDModel::dfde(const double, const double V=0.0)=0
virtual double OneDModel::dfdv(const double, const double V=0.0)=0
virtual double OneDModel::distf(const double, const double V=0.0)=0
double OneDModel::get_density(const double x, const double y, const double z)
The density at (x, y, z)
References get_density.
virtual double OneDModel::get_density(const double)=0
Referenced by get_density.
virtual double OneDModel::get_dpot(const double)=0
virtual double OneDModel::get_dpot2(const double)=0
double OneDModel::get_mass(const double x, const double y, const double z)
Get the mass inside of position (x, y, z) (this is ambiguous in general and will depend on the model)
References get_mass.
virtual double OneDModel::get_mass(const double)=0
Referenced by get_mass.
virtual double OneDModel::get_max_radius(void)=0
virtual double OneDModel::get_min_radius(void)=0
double OneDModel::get_pot(const double x, const double y, const double z)
The potential at (x, y, z)
References get_pot.
virtual double OneDModel::get_pot(const double)=0
Referenced by get_pot.
virtual tuple< double, double > OneDModel::get_pot_dpot(const double)=0
virtual double OneDModel::get_scale_height(void)=0