CBSphere
double CBSphere::rbmax
Referenced by rb_max.
double CBSphere::rbmin
Referenced by rb_min.
CBSphere::CBSphere(void)
double CBSphere::d_r_to_rb(double const)
void CBSphere::dens(const int nn, const int l, const double r, Eigen::VectorXd &a)
double CBSphere::dens(const int nn, const int l, const double rb)
Referenced by densR.
double CBSphere::densR(const int nn, const int l, const double r)
References dens, r_to_rb.
double CBSphere::krnl(const int nn, const int l)
double CBSphere::norm(const int nn, const int l)
void CBSphere::potl(const int nn, const int l, const double r, Eigen::VectorXd &a)
double CBSphere::potl(const int nn, const int l, const double rb)
Referenced by potlR, potlRZ.
double CBSphere::potlR(const int nn, const int l, const double r)
References potl, r_to_rb.
double CBSphere::potlRZ(const int nn, const int l, const double r, const double z)
References potl, r_to_rb.
double CBSphere::r_to_rb(double const)
Referenced by densR, potlR, potlRZ.
double CBSphere::rb_max(void)
References rbmax.
double CBSphere::rb_min(void)
References rbmin.
double CBSphere::rb_to_r(double const)
virtual CBSphere::~CBSphere()