CBDisk
using CBDisk::Disk2d = std::shared_ptr<EmpCyl2d::ModelCyl>
Background instance.
Disk2d CBDisk::disk
Referenced by background.
double CBDisk::fac1
Potential, force, and density scale factors.
double CBDisk::fac2
int CBDisk::mmax
string CBDisk::model
int CBDisk::numz
Referenced by set_numz.
double CBDisk::scale
Parameters.
const std::set<std::string> CBDisk::valid_keys
Valid keys for YAML configurations.
virtual std::tuple< double, double, double > CBDisk::background(double r, double z)
Background evaluation.
References disk.
void CBDisk::dens(const int m, const double r, Eigen::VectorXd &a)
double CBDisk::dens(const int n, const int m, const double r)
double CBDisk::dphi(const int n, const int m, const double r)
double CBDisk::dpot(const int n, const int m, const double r)
void CBDisk::get_dens(double r, double z, Eigen::MatrixXd &p, int tid)
Get derivative of potential r is the evaluation radius z is the evaluation height d will be returned array in harmonics l and radial order n for the density tid is the thread enumerator that allows the function to provide some thread safety
void CBDisk::get_dpotl(double r, double z, Eigen::MatrixXd &p, Eigen::MatrixXd &dpr, Eigen::MatrixXd &dpz, int tid)
Get derivative of potential r is the evaluation radius z is the evaluation height p will be returned array in harmonics l and radial order n for the potential dpr will be returned array in harmonics l and radial order n for the derivative of the potential dpz will be returned array in harmonics l and radial order n for the derivative of the potential tid is the thread enumerator that allows the function to provide some thread safety
void CBDisk::get_potl(double r, double z, Eigen::MatrixXd &p, int tid)
Get derivative of potential r is the evaluation radius z is the evaluation height p will be returned array in harmonics l and radial order n for the potential tid is the thread enumerator that allows the function to provide some thread safety
Referenced by get_pot.
void CBDisk::get_potl_dens(double r, double z, Eigen::MatrixXd &p, Eigen::MatrixXd &d, int tid)
Get the potential and density r is the evaluation radius p will be returned array in harmonics l and radial order n for the potential d will be returned array in harmonics l and radial order n for the density tid is the thread enumerator that allows the function to provide some thread safety
virtual double CBDisk::getRtable()
Required maximum table radious (no limit here)
void CBDisk::initialize(void)
Initialize method.
double CBDisk::norm(const int n, const int m)
void CBDisk::orthoCheck()
Sanity check.
double CBDisk::phif(const int n, const int m, const double r)
double CBDisk::phif(const int n, const int m, const double r)
2D Clutton-Brock basis
void CBDisk::potl(const int m, const double r, Eigen::VectorXd &a)
double CBDisk::potl(const int n, const int m, const double r)
void CBDisk::setBackground()
Set background from YAML.
CBDisk::CBDisk(Component *c0, const YAML::Node &conf, MixtureBasis *m=0)
Constructor c0 is the instantiating caller (Component) conf passes any parameters to basis instance scale is the radius for coordinate scaling
CBDisk::CBDisk(void)
double CBDisk::d_r_to_rb(double const r)
double CBDisk::dens(const int n, const int m, const double r)
Referenced by densR.
void CBDisk::dens(const int n, const int m, const double r, Eigen::VectorXd &a)
double CBDisk::densR(const int n, const int m, const double r)
References dens.
double CBDisk::krnl(const int n, const int m)
double CBDisk::norm(const int n, const int m)
double CBDisk::potl(const int n, const int m, const double r)
Referenced by potlR.
void CBDisk::potl(const int n, const int m, const double r, Eigen::VectorXd &a)
double CBDisk::potlR(const int n, const int m, const double r)
References potl.
double CBDisk::potlRZ(const int n, const int m, const double r, const double z)
double CBDisk::r_to_rb(double const r)
double CBDisk::rb_max(void)
double CBDisk::rb_min(void)
double CBDisk::rb_to_r(double const r)
void CBDisk::set_numz(int n)
References numz.
virtual CBDisk::~CBDisk()
Destructor.
void CBDisk::get_pot(Eigen::MatrixXd &Vc, Eigen::MatrixXd &Vs, double r, double z)
Clutton-Brock potential.
References get_potl.