KDtree::kdtree
using KDtree::kdtree< coordinate_type, dimensions >::cache = Cache<double, node*>
using KDtree::kdtree< coordinate_type, dimensions >::point_type = point<coordinate_type, dimensions>
std::vector<node> KDtree::kdtree< coordinate_type, dimensions >::nodes_
Referenced by KDtree::kdtree< coordinate_type, dimensions >::empty, KDtree::kdtree< coordinate_type, dimensions >::kdtree, KDtree::kdtree< coordinate_type, dimensions >::kdtree, KDtree::kdtree< coordinate_type, dimensions >::make_tree.
node* KDtree::kdtree< coordinate_type, dimensions >::root_
Referenced by KDtree::kdtree< coordinate_type, dimensions >::getPartition, KDtree::kdtree< coordinate_type, dimensions >::kdtree, KDtree::kdtree< coordinate_type, dimensions >::kdtree, KDtree::kdtree< coordinate_type, dimensions >::nearestList, KDtree::kdtree< coordinate_type, dimensions >::nearestN.
size_t KDtree::kdtree< coordinate_type, dimensions >::visited_
Referenced by KDtree::kdtree< coordinate_type, dimensions >::kdtree, KDtree::kdtree< coordinate_type, dimensions >::kdtree, KDtree::kdtree< coordinate_type, dimensions >::nearestList, KDtree::kdtree< coordinate_type, dimensions >::nearestN, KDtree::kdtree< coordinate_type, dimensions >::nearestN, KDtree::kdtree< coordinate_type, dimensions >::visited.
void KDtree::kdtree< coordinate_type, dimensions >::accum(node *root, std::vector< std::vector< unsigned long > > &ret, unsigned cur)
References KDtree::kdtree< coordinate_type, dimensions >::accum, KDtree::point< coordinate_type, dimensions >::indx, KDtree::kdtree< coordinate_type, dimensions >::node::left_, KDtree::kdtree< coordinate_type, dimensions >::node::point_, KDtree::kdtree< coordinate_type, dimensions >::node::right_.
Referenced by KDtree::kdtree< coordinate_type, dimensions >::accum, KDtree::kdtree< coordinate_type, dimensions >::walk.
node * KDtree::kdtree< coordinate_type, dimensions >::make_tree(size_t begin, size_t end, size_t index)
References KDtree::kdtree< coordinate_type, dimensions >::make_tree, KDtree::kdtree< coordinate_type, dimensions >::nodes_.
Referenced by KDtree::kdtree< coordinate_type, dimensions >::kdtree, KDtree::kdtree< coordinate_type, dimensions >::kdtree, KDtree::kdtree< coordinate_type, dimensions >::make_tree.
void KDtree::kdtree< coordinate_type, dimensions >::nearestN(node *root, const point_type &point, size_t index, int N, cache &best_)
References KDtree::Cache< key_t, value_t >::add, KDtree::kdtree< coordinate_type, dimensions >::node::distance, KDtree::point< coordinate_type, dimensions >::get, KDtree::kdtree< coordinate_type, dimensions >::node::get, KDtree::kdtree< coordinate_type, dimensions >::node::left_, KDtree::kdtree< coordinate_type, dimensions >::nearestN, KDtree::kdtree< coordinate_type, dimensions >::node::right_, KDtree::kdtree< coordinate_type, dimensions >::visited_.
Referenced by KDtree::kdtree< coordinate_type, dimensions >::nearestList, KDtree::kdtree< coordinate_type, dimensions >::nearestN, KDtree::kdtree< coordinate_type, dimensions >::nearestN.
void KDtree::kdtree< coordinate_type, dimensions >::walk(node *root, std::vector< std::vector< unsigned long > > &ret, unsigned int cur, unsigned int lev, unsigned int level)
References KDtree::kdtree< coordinate_type, dimensions >::accum, KDtree::point< coordinate_type, dimensions >::indx, KDtree::kdtree< coordinate_type, dimensions >::node::left_, KDtree::kdtree< coordinate_type, dimensions >::node::point_, KDtree::kdtree< coordinate_type, dimensions >::node::right_, KDtree::kdtree< coordinate_type, dimensions >::walk.
Referenced by KDtree::kdtree< coordinate_type, dimensions >::getPartition, KDtree::kdtree< coordinate_type, dimensions >::walk.
double KDtree::kdtree< coordinate_type, dimensions >::distance(cache &best_) const
Returns the distance between the input point and return value from the last call to nearest().
bool KDtree::kdtree< coordinate_type, dimensions >::empty() const
Returns true if the tree is empty, false otherwise.
References KDtree::kdtree< coordinate_type, dimensions >::nodes_.
std::vector< double > KDtree::kdtree< coordinate_type, dimensions >::getDist(cache &best_)
std::vector< std::vector< unsigned long > > KDtree::kdtree< coordinate_type, dimensions >::getPartition(unsigned level)
References KDtree::kdtree< coordinate_type, dimensions >::root_, KDtree::kdtree< coordinate_type, dimensions >::walk.
KDtree::kdtree< coordinate_type, dimensions >::kdtree(const kdtree &)=delete
Copy constructor2.
KDtree::kdtree< coordinate_type, dimensions >::kdtree(func &&f, size_t n)
Constructor taking a function object that generates points. The function object will be called n times to populate the tree. f function that returns a point n number of points to add
References KDtree::kdtree< coordinate_type, dimensions >::make_tree, KDtree::kdtree< coordinate_type, dimensions >::nodes_, KDtree::kdtree< coordinate_type, dimensions >::root_, KDtree::kdtree< coordinate_type, dimensions >::visited_.
KDtree::kdtree< coordinate_type, dimensions >::kdtree(iterator begin, iterator end)
Constructor taking a pair of iterators. Adds each point in the range [begin, end) to the tree. begin start of range end end of range
References KDtree::kdtree< coordinate_type, dimensions >::make_tree, KDtree::kdtree< coordinate_type, dimensions >::nodes_, KDtree::kdtree< coordinate_type, dimensions >::root_, KDtree::kdtree< coordinate_type, dimensions >::visited_.
std::tuple< std::vector< point_type >, double, cache > KDtree::kdtree< coordinate_type, dimensions >::nearestList(const point_type &pt, int N)
Finds the nearest N points in the tree to the given point. It is not valid to call this function if the tree is empty. pt a point N is the number of nearest points Returns: tuple of the nearest point list and the radius of the Nth point
References KDtree::kdtree< coordinate_type, dimensions >::nearestN, KDtree::kdtree< coordinate_type, dimensions >::root_, KDtree::kdtree< coordinate_type, dimensions >::visited_.
std::tuple< point_type, double, double, cache > KDtree::kdtree< coordinate_type, dimensions >::nearestN(const point_type &pt, int N)
Finds the nearest N points in the tree to the given point. It is not valid to call this function if the tree is empty. pt a point N is the number of nearest points Returns: tuple of the first points, summed weight, and the radius of the Nth point
References KDtree::kdtree< coordinate_type, dimensions >::nearestN, KDtree::kdtree< coordinate_type, dimensions >::root_, KDtree::kdtree< coordinate_type, dimensions >::visited_.
kdtree & KDtree::kdtree< coordinate_type, dimensions >::operator=(const kdtree &)=delete
size_t KDtree::kdtree< coordinate_type, dimensions >::visited() const
Returns the number of nodes visited by the last call to nearest().
References KDtree::kdtree< coordinate_type, dimensions >::visited_.