QDHT
Eigen::VectorXd QDHT::Jp
Jp vector.
Eigen::VectorXd QDHT::k
Referenced by getK.
int QDHT::N
N is number of knots.
double QDHT::nu
nu is Bessel function order
double QDHT::R
Dimension 1 scale.
Eigen::VectorXd QDHT::r
R and K vectors.
Referenced by getR.
double QDHT::S
Total bandwidth.
Eigen::MatrixXd QDHT::T
Transform matrix.
double QDHT::V
Dimension 2 scale.
Eigen::VectorXd QDHT::zeros
Will contain the zeros of the Bessel function of order nu.
bool QDHT::debug
For checking unitarity (default: false)
void QDHT::check()
Check solution.
const Eigen::VectorXd & QDHT::getK()
Compute the transform coordinates (e.g. spatial frequencies)
References k.
Referenced by PotRZ::Sk::operator().
const Eigen::VectorXd & QDHT::getR()
Compute the input coordinates (e.g. radii)
References r.
Referenced by PotRZ::operator(), PotRZ::Sk::operator().
double QDHT::operator()(double r, Eigen::VectorXd &v)
Inverse Hankel transform at r.
Eigen::VectorXd QDHT::operator()(Eigen::VectorXd &v, bool forward=true)
Compute the forward or backward Hankel transform.
QDHT::QDHT()
Null constructor.
QDHT::QDHT(int M, int N, double R)
Constructor M is the harmonic order N is the number of knots R is the radius at which the input function is zero
QDHT::~QDHT()
Destructor.