PVQuad
Eigen::VectorXd PVQuad::chrs
Referenced by mu.
Eigen::VectorXd PVQuad::coefs
Eigen::VectorXd PVQuad::eign
Referenced by root.
int PVQuad::n
Eigen::VectorXd PVQuad::nrml
Referenced by norm.
std::vector<Eigen::VectorXd> PVQuad::poly
Referenced by ovec.
Eigen::VectorXd & PVQuad::get_coefs(Eigen::VectorXd &)
Referenced by return_coefs.
void PVQuad::get_eigenvalues(void)
double PVQuad::get_integral(double)
Referenced by return_pv, return_pv, return_pv.
void PVQuad::get_orthopolies(void)
double PVQuad::q0(double x)
double PVQuad::mu(int i)
References chrs.
double PVQuad::norm(int i)
References nrml.
Eigen::VectorXd & PVQuad::ovec(int i)
References poly.
PVQuad::PVQuad(int N=10)
Eigen::VectorXd & PVQuad::return_coefs(Eigen::VectorXd &input)
References get_coefs.
Eigen::VectorXd & PVQuad::return_coefs(std::function< double(double)> func)
Referenced by return_pv, return_pv.
double PVQuad::return_pv(double lambda)
References get_integral.
double PVQuad::return_pv(double lambda, Eigen::VectorXd &input)
References get_integral, return_coefs.
double PVQuad::return_pv(double lambda, std::function< double(double)> func)
References get_integral, return_coefs.
double PVQuad::root(int i)
References eign.