OneDModelTable
Spline1d OneDModelTable::dens
int OneDModelTable::even
double OneDModelTable::half_height
Referenced by get_scale_height.
Spline1d OneDModelTable::mass
Referenced by get_max_radius, get_min_radius.
int OneDModelTable::num
Referenced by grid_size.
int OneDModelTable::numdf
std::vector<double> OneDModelTable::params
Referenced by get_num_param, get_param.
Spline1d OneDModelTable::pot
double OneDModelTable::get_density(const double)
double OneDModelTable::get_dpot(const double)
Referenced by Sech2Halo::get_dpot.
double OneDModelTable::get_dpot2(const double)
Referenced by Sech2Halo::get_dpot2.
double OneDModelTable::get_mass(const double)
double OneDModelTable::get_max_radius(void)
References mass, Spline1d::xhi.
double OneDModelTable::get_min_radius(void)
References mass, Spline1d::xlo.
const int OneDModelTable::get_num_param(void)
References params.
const double OneDModelTable::get_param(int i)
References params.
double OneDModelTable::get_pot(const double)
Referenced by Sech2Halo::get_pot.
tuple< double, double > OneDModelTable::get_pot_dpot(const double)
Referenced by Sech2Halo::get_pot_dpot.
double OneDModelTable::get_scale_height(void)
References half_height.
int OneDModelTable::grid_size(void)
References num.
OneDModelTable::OneDModelTable()
OneDModelTable::OneDModelTable(int num, double *r, double *d, double *m, double *p, string ID="")
OneDModelTable::OneDModelTable(string filename, int PARM=0)