DiskWithHalo
std::shared_ptr<AxiSymModel> DiskWithHalo::d
Referenced by DiskWithHalo, DiskWithHalo, get_density, get_dpot, get_dpot2, get_mass, get_max_radius, get_min_radius, get_pot, get_pot_dpot.
std::shared_ptr<AxiSymModel> DiskWithHalo::h
Referenced by DiskWithHalo, DiskWithHalo, get_dpot, get_dpot2, get_max_radius, get_min_radius, get_pot, get_pot_dpot.
double DiskWithHalo::d2fde2(double E, double L) override
References MassModel::bomb.
double DiskWithHalo::dfde(double E, double L) override
References MassModel::bomb.
double DiskWithHalo::dfdl(double E, double L) override
References MassModel::bomb.
DiskWithHalo::DiskWithHalo()
DiskWithHalo::DiskWithHalo(const DiskWithHalo &t)
References d, MassModel::dim, AxiSymModel::dist_defined, h, MassModel::ModelID.
DiskWithHalo::DiskWithHalo(std::shared_ptr< AxiSymModel > D, std::shared_ptr< AxiSymModel > H)
References d, MassModel::dim, AxiSymModel::dist_defined, h, MassModel::ModelID.
double DiskWithHalo::distf(double E, double L) override
References MassModel::bomb.
virtual double DiskWithHalo::get_density(const double r) override
References d.
Referenced by get_density.
double DiskWithHalo::get_density(const double x1, const double x2, const double x3) override
The density at (x, y, z)
References get_density.
virtual double DiskWithHalo::get_dpot(const double r) override
References d, h.
virtual double DiskWithHalo::get_dpot2(const double r) override
References d, h.
virtual double DiskWithHalo::get_mass(const double r) override
Access the profile.
References d.
Referenced by get_mass.
double DiskWithHalo::get_mass(const double x1, const double x2, const double x3) override
Get the mass inside of position (x, y, z) (this is ambiguous in general and will depend on the model)
References get_mass.
double DiskWithHalo::get_max_radius(void) override
References d, h.
double DiskWithHalo::get_min_radius(void) override
References d, h.
virtual double DiskWithHalo::get_pot(const double r) override
References d, h.
Referenced by get_pot.
double DiskWithHalo::get_pot(const double x1, const double x2, const double x3) override
The potential at (x, y, z)
References get_pot.
virtual void DiskWithHalo::get_pot_dpot(const double r, double &ur, double &dur) override
References d, h.