coulombSelect
std::vector<double> coulombSelect::cA
Referenced by coulombSelect, eval.
std::vector<double> coulombSelect::cT
Array grids.
Referenced by coulombSelect, eval.
const int coulombSelect::numT
Tau evaluation grid.
Referenced by coulombSelect.
const double coulombSelect::tau_f
Referenced by coulombSelect, eval.
const double coulombSelect::tau_i
Limiting values for tau evaluation for asymptotic and extreme values
Referenced by coulombSelect, eval.
const double coulombSelect::tau_m
Referenced by eval.
const double coulombSelect::tau_z
Referenced by eval.
double coulombSelect::deriv(double x)
Referenced by func.
double coulombSelect::f(double x)
Referenced by func.
double coulombSelect::func(double tau, double x)
References deriv, f.
Referenced by coulombSelect.
coulombSelect::coulombSelect()
Constructor.
References cA, cT, func, numT, tau_f, tau_i.
double coulombSelect::eval(double tau)
Evaluate A given tau.
References cA, cT, tau_f, tau_i, tau_m, tau_z.
Referenced by operator().
double coulombSelect::operator()(double tau, double U)
Select tau given random number U in [0,1)
References eval.