Sech2mu
double Sech2mu::dispx
Referenced by dfde, dfdv, distf, Sech2mu, Sech2mu.
double Sech2mu::dispz
Referenced by dfde, dfdv, distf, get_dpot, get_dpot2, get_pot, get_pot_dpot, Sech2mu, Sech2mu, setMu.
double Sech2mu::dnorm
Referenced by get_density, Sech2mu, Sech2mu, setMu.
double Sech2mu::fnorm
Referenced by dfde, dfdv, distf, Sech2mu, Sech2mu, setMu.
double Sech2mu::h
Referenced by get_density, get_dpot, get_dpot2, get_mass, get_max_radius, get_pot, get_pot_dpot, get_scale_height, Sech2mu, Sech2mu, setMu.
double Sech2mu::knorm
Referenced by get_pot, get_pot_dpot, Sech2mu, Sech2mu, setMu.
double Sech2mu::mu
Referenced by get_mass, Sech2mu, Sech2mu, setMu.
double Sech2mu::HMAX
Referenced by get_max_radius, set_hmax.
double Sech2mu::dfde(const double E, const double p)
References dispx, dispz, fnorm.
double Sech2mu::dfdv(const double E, const double p)
References dispx, dispz, fnorm.
double Sech2mu::distf(const double E, const double p)
References dispx, dispz, fnorm.
double Sech2mu::get_density(const double x, const double y, const double z)
The density at (x, y, z)
References get_density.
double Sech2mu::get_density(const double z)
References dnorm, h.
Referenced by get_density.
double Sech2mu::get_dpot(const double z)
References dispz, h.
double Sech2mu::get_dpot2(const double z)
References dispz, h.
double Sech2mu::get_mass(const double x, const double y, const double z)
Get the mass inside of position (x, y, z) (this is ambiguous in general and will depend on the model)
References get_mass.
double Sech2mu::get_mass(const double z)
References h, mu.
Referenced by get_mass.
double Sech2mu::get_max_radius(void)
References h, HMAX.
double Sech2mu::get_min_radius(void)
double Sech2mu::get_pot(const double x, const double y, const double z)
The potential at (x, y, z)
References get_pot.
double Sech2mu::get_pot(const double z)
References dispz, h, knorm.
Referenced by get_pot.
void Sech2mu::get_pot_dpot(const double z, double &p, double &dp)
References dispz, h, knorm.
double Sech2mu::get_scale_height(void)
References h.
Sech2mu::Sech2mu(const double DISPZ, const double H, const double DISPX=1.0)
References dispx, dispz, OneDModel::dist_defined, dnorm, fnorm, h, knorm, mu.
Sech2mu::Sech2mu(void)
References dispx, dispz, OneDModel::dist_defined, dnorm, fnorm, h, knorm, mu.
void Sech2mu::setMu(double Sigma0)
References dispz, OneDModel::dist_defined, dnorm, fnorm, h, knorm, mu.
static void Sech2mu::set_hmax(double hmax)
References HMAX.