Cheby1d
double Cheby1d::a
double Cheby1d::b
std::vector<double> Cheby1d::c
Referenced by eval, eval.
std::vector<double> Cheby1d::c1
Referenced by deriv, deriv2, eval.
std::vector<double> Cheby1d::c2
bool Cheby1d::defined
Referenced by deriv, deriv2, eval, eval, integral.
int Cheby1d::n
double Cheby1d::xmax
Referenced by xhi.
double Cheby1d::xmin
Referenced by xlo.
void Cheby1d::chder(std::vector< double > &cin, std::vector< double > &cder)
double Cheby1d::chebev(double x, std::vector< double > &cin)
Referenced by deriv, deriv2, eval, eval.
double Cheby1d::chebint(double x)
Referenced by integral.
void Cheby1d::bomb(const char *,...)
Handle error.
Referenced by deriv, deriv2, eval, eval, integral.
Cheby1d::Cheby1d()
Null constructor.
Cheby1d::Cheby1d(const double A, const double B, const Eigen::VectorXd &x, const Eigen::VectorXd &y, int N)
Construct with Eigen input (N is Chebyshev order)
Cheby1d::Cheby1d(const double A, const double B, std::vector< double > &x, std::vector< double > &y, int N)
Construct with std::vector input (N is Chebyshev order)
Cheby1d::Cheby1d(const Eigen::VectorXd &x, const Eigen::VectorXd &y, int N)
Construct with Eigen input (N is Chebyshev order) using data limits.
Cheby1d::Cheby1d(std::vector< double > &x, std::vector< double > &y, int N)
Construct with std::vector input (N is Chebyshev order) using data limits.
double Cheby1d::deriv(const double &x)
Evaluate first derivative.
References bomb, c1, chebev, defined.
Referenced by eval.
double Cheby1d::deriv2(const double &x)
Evaluate the second derivative.
References bomb, c1, chebev, defined.
double Cheby1d::eval(const double &x)
Evaluate the interpolant.
References bomb, c, chebev, defined.
void Cheby1d::eval(const double &x, double &val, double &deriv)
Evaluate the interpolant and its first derivative.
References bomb, c, c1, chebev, defined, deriv.
double Cheby1d::integral(const double &x)
Evaluate integral of interpolant.
References bomb, chebint, defined.
void Cheby1d::new_data(std::vector< double > &X, std::vector< double > &Y, int N)
Update the data.
void Cheby1d::new_func(std::function< double(double)> func, double A, double B, int N)
Generate interpolant from a function.
void Cheby1d::new_limits(double A, double B)
Update the data limits.
Cheby1d & Cheby1d::operator=(const Cheby1d &)
Copy constructor.
double Cheby1d::xhi()
References xmax.
double Cheby1d::xlo()
Data limits.
References xmin.
Cheby1d::~Cheby1d()
Destructor.