MonotCubicInterpolator
std::map<double, double> MonotCubicInterpolator::data
Referenced by getMaximumX, getMinimumX, getSize.
std::map<double, double> MonotCubicInterpolator::ddata
bool MonotCubicInterpolator::decreasing
Referenced by isMonotoneDecreasing.
bool MonotCubicInterpolator::increasing
Referenced by isMonotoneIncreasing.
bool MonotCubicInterpolator::monotone
Referenced by isMonotone, isMonotoneDecreasing, isMonotoneIncreasing.
bool MonotCubicInterpolator::monotoneCached
Referenced by isMonotone, isMonotoneDecreasing, isMonotoneIncreasing.
bool MonotCubicInterpolator::strictlyDecreasing
Referenced by isStrictlyDecreasing.
bool MonotCubicInterpolator::strictlyIncreasing
Referenced by isStrictlyIncreasing.
bool MonotCubicInterpolator::strictlyMonotone
Referenced by isStrictlyDecreasing, isStrictlyIncreasing, isStrictlyMonotone.
bool MonotCubicInterpolator::strictlyMonotoneCached
Referenced by isStrictlyDecreasing, isStrictlyIncreasing, isStrictlyMonotone.
void MonotCubicInterpolator::addPair(double newx, double newf)
newx New x point newf New f(x) point Adds a new datapoint to the function. This causes all the derivatives at all points of the functions to be recomputed and then adjusted for monotone cubic interpolation. If this function ever enters a critical part of any code, the locality of the algorithm for monotone adjustment must be exploited.
void MonotCubicInterpolator::chopFlatEndpoints()
Wrapper function for chopFlatEndpoints(const double) providing a default epsilon parameter
References chopFlatEndpoints.
Referenced by chopFlatEndpoints.
void MonotCubicInterpolator::chopFlatEndpoints(const double)
Checks if the function curve is flat at the endpoints, chop off endpoint data points if that is the case. The notion of "flat" is determined by the input parameter "epsilon" Values whose difference are less than epsilon are regarded as equal. This is implemented to be able to obtain a strictly monotone curve from a data set that is strictly monotone except at the endpoints. Example: The data points (1,3), (2,3), (3,4), (4,5), (5,5), (6,5) will become (2,3), (3,4), (4,5) Assumes at least 3 datapoints. If less than three, this function is a noop.
double MonotCubicInterpolator::evaluate(double x) const
x x value Returns f(x) for given x (input). Interpolates (monotone cubic or linearly) if necessary. Extrapolates using the constants f(x_min) or f(x_max) if input x is outside (x_min, x_max) f(x) for a given x
Referenced by operator().
double MonotCubicInterpolator::evaluate(double x, double &errorestimate_output) const
x x value errorestimate_output Returns f(x) and an error estimate for given x (input). Interpolates (linearly) if necessary. Throws an exception if extrapolation would be necessary for evaluation. We do not want to do extrapolation (yet). The error estimate for x1 < x < x2 is (x2 - x1)^2/8 * f''(x) where f''(x) is evaluated using the stencil (1 -2 1) using either (x0, x1, x2) or (x1, x2, x3); Throws an exception if the table contains only two x-values. NOT IMPLEMENTED YET!
std::vector< double > MonotCubicInterpolator::get_fVector() const
Provide a copy of tghe function data as a vector Unspecified order, but corresponds to get_xVector f values as a vector
std::vector< double > MonotCubicInterpolator::get_xVector() const
Provide a copy of the x-data as a vector Unspecified order, but corresponds to get_fVector. x values as a vector
std::pair< double, double > MonotCubicInterpolator::getMaximumF() const
Maximum f-value, returns both x and f in a pair. x value corresponding to maximum f value maximum f value
std::pair< double, double > MonotCubicInterpolator::getMaximumX() const
Maximum x-value, returns both x and f in a pair. maximum x value f(maximum x value)
References data.
std::pair< double, double > MonotCubicInterpolator::getMinimumF() const
Minimum f-value, returns both x and f in a pair x value corresponding to minimal f value minimum f value
std::pair< double, double > MonotCubicInterpolator::getMinimumX() const
Minimum x-value, returns both x and f in a pair. minimum x value f(minimum x value)
References data.
std::pair< double, double > MonotCubicInterpolator::getMissingX() const
Returns an x-value that is believed to yield the best improvement in global accuracy for the interpolation if computed. Searches for the largest jump in f-values, and returns a x value being the average of the two x-values representing the f-value-jump. New x value beleived to yield the best improvement in global accuracy Maximal difference
int MonotCubicInterpolator::getSize() const
Number of datapoint pairs in this object
References data.
bool MonotCubicInterpolator::isMonotone() const
Determines if the current function-value-data is monotone. True if f(x) is monotone, else False
References computeInternalFunctionData, monotone, monotoneCached.
bool MonotCubicInterpolator::isMonotoneDecreasing() const
Determines if the current function-value-data is monotone and decreasing True if f(x) is monotone and decreasing, else False
References computeInternalFunctionData, decreasing, monotone, monotoneCached.
bool MonotCubicInterpolator::isMonotoneIncreasing() const
Determines if the current function-value-data is monotone and increasing. True if f(x) is monotone and increasing, else False
References computeInternalFunctionData, increasing, monotone, monotoneCached.
bool MonotCubicInterpolator::isStrictlyDecreasing()
Determines if the current function-value-data is strictly decreasing. This is a utility function for outsiders if they want to invert the data for example. True if f(x) is strictly decreasing, else False
References computeInternalFunctionData, strictlyDecreasing, strictlyMonotone, strictlyMonotoneCached.
bool MonotCubicInterpolator::isStrictlyIncreasing()
Determines if the current function-value-data is strictly increasing. This is a utility function for outsiders if they want to invert the data for example. True if f(x) is strictly increasing, else False
References computeInternalFunctionData, strictlyIncreasing, strictlyMonotone, strictlyMonotoneCached.
bool MonotCubicInterpolator::isStrictlyMonotone()
Determines if the current function-value-data is strictly monotone. This is a utility function for outsiders if they want to invert the data for example. True if f(x) is strictly monotone, else False
References computeInternalFunctionData, strictlyMonotone, strictlyMonotoneCached.
MonotCubicInterpolator::MonotCubicInterpolator()
No input, an empty function object is created. This object must be treated with care until populated.
MonotCubicInterpolator::MonotCubicInterpolator(const char *datafilename)
datafilename A datafile with the x values and the corresponding f(x) values Accepts a filename as input and parses this file for two-column floating point data, interpreting the data as representing function values x and f(x). Ignores all lines not conforming to <whitespace><float><whitespace><float><whatever><newline> All commas in the file will be treated as spaces when parsing.
References read.
MonotCubicInterpolator::MonotCubicInterpolator(const char *datafilename, int xColumn, int fColumn)
datafilename data file XColumn x values fColumn f values Accepts a filename as input, and parses the chosen columns in that file.
References read.
MonotCubicInterpolator::MonotCubicInterpolator(const std::string &datafilename)
datafilename A datafile with the x values and the corresponding f(x) values Accepts a filename as input and parses this file for two-column floating point data, interpreting the data as representing function values x and f(x). Ignores all lines not conforming to <whitespace><float><whitespace><float><whatever><newline>
References read.
MonotCubicInterpolator::MonotCubicInterpolator(const std::string &datafilename, int xColumn, int fColumn)
datafilename data file XColumn x values fColumn f values Accepts a filename as input, and parses the chosen columns in that file.
References read.
MonotCubicInterpolator::MonotCubicInterpolator(const std::vector< double > &x, const std::vector< double > &f)
x vector of x values f vector of corresponding f values Accepts two equal-length vectors as input for constructing the interpolation object. First vector is the x-values, the second vector is the function values
double MonotCubicInterpolator::operator()(double x) const
x x value Returns f(x) for given x (input). Interpolates (monotone cubic or linearly) if necessary. Extrapolates using the constants f(x_min) or f(x_max) if input x is outside (x_min, x_max) f(x) for a given x
References evaluate.
bool MonotCubicInterpolator::read(const std::string &datafilename)
datafilename A datafile with the x values and the corresponding f(x) values Accepts a filename as input and parses this file for two-column floating point data, interpreting the data as representing function values x and f(x). returns true on success All commas in file will be treated as spaces when parsing Ignores all lines not conforming to <whitespace><float><whitespace><float><whatever><newline>
References read.
Referenced by MonotCubicInterpolator, MonotCubicInterpolator, MonotCubicInterpolator, MonotCubicInterpolator, read.
bool MonotCubicInterpolator::read(const std::string &datafilename, int xColumn, int fColumn)
datafilename data file XColumn x values fColumn f values Accepts a filename as input, and parses the chosen columns in that file.
void MonotCubicInterpolator::scaleData(double factor)
factor Scaling constant Scale all the function value data by a constant
void MonotCubicInterpolator::shrinkFlatAreas()
Wrapper function for shrinkFlatAreas(const double) providing a default epsilon parameter
References shrinkFlatAreas.
Referenced by shrinkFlatAreas.
void MonotCubicInterpolator::shrinkFlatAreas(const double)
If function is monotone, but not strictly monotone, this function will remove datapoints from intervals with zero derivative so that the curve become strictly monotone. Example The data points (1,2), (2,3), (3,4), (4,4), (5,5), (6,6) will become (1,2), (2,3), (3,4), (5,5), (6,6) Assumes at least two datapoints, if one or zero datapoint, this is a noop.
std::string MonotCubicInterpolator::toString() const
Constructs a string containing the data in a table a string containing the data in a table
void MonotCubicInterpolator::adjustDerivativesForMonotoneness() const
Adjusts the derivative values (ddata) so that we can guarantee that the resulting piecewise Hermite polymial is monotone. This is done according to the algorithm of Fritsch and Carlsson 1980, see Section 4, especially the two last lines.
void MonotCubicInterpolator::computeInternalFunctionData() const
Referenced by isMonotone, isMonotoneDecreasing, isMonotoneIncreasing, isStrictlyDecreasing, isStrictlyIncreasing, isStrictlyMonotone.
void MonotCubicInterpolator::computeSimpleDerivatives() const
Computes initial derivative values using centered (second order) difference for internal datapoints, and one-sided derivative for endpoints The internal datastructure map<double,double> ddata is populated by this method.
double MonotCubicInterpolator::H00(double t) const
double MonotCubicInterpolator::H01(double t) const
double MonotCubicInterpolator::H10(double t) const
double MonotCubicInterpolator::H11(double t) const
bool MonotCubicInterpolator::isMonotoneCoeff(double alpha, double beta) const
Checks if the coefficient alpha and beta is in the region that guarantees monotoneness of the derivative values they represent See Fritsch and Carlson 1980, Lemma 2, alternatively Step 5 in Wikipedia's article on Monotone cubic interpolation.