Timer
std::chrono::high_resolution_clock::time_point Timer::begin
Time structures (will initialize to zero by default)
Referenced by getTime, reset, start, stop, Timer.
std::chrono::high_resolution_clock::time_point Timer::end
Referenced by getTime, stop, Timer.
double Timer::rtime
The time measured so far.
Referenced by getTime, reset, stop, Timer, Timer.
bool Timer::started
Indicate whether the timer has been started.
Referenced by getTime, isStarted, reset, start, stop, Timer, Timer.
double Timer::getTime()
Return time measured up to this point.
References begin, end, rtime, started.
Referenced by RunningTime::append, Component::get_time_sofar, BarrierWrapper::getTime, RunningTime::lap, operator().
bool Timer::isStarted()
Return the status of the timer.
References started.
double Timer::operator()()
Return time measured up to this point.
References getTime.
void Timer::reset()
Reset the timer, this will reset the time measured to 0 and reset the zero point if the timer is active
References begin, rtime, started.
Referenced by BarrierWrapper::getTime, RunningTime::Stop.
void Timer::start()
Start timer, if already started then do nothing.
References begin, started.
Referenced by RunningTime::Start.
double Timer::stop()
Stop timer and return time measured so far. If timer was stopped the time returned will be the current elapsed time.
References begin, end, rtime, started.
Referenced by RunningTime::Stop.
Timer::Timer()
Constructor.
References rtime, started.
Timer::Timer(const Timer &t)
Copy consructor.
References begin, end, rtime, started.