PSP
static const unsigned long PSP::magic
static const unsigned long PSP::mmask
static const unsigned long PSP::nmask
PSPstanza * PSP::cur
Referenced by GetNamed.
MasterHeader PSP::header
Referenced by CurrentTime.
std::ifstream PSP::in
Referenced by init, ~PSP.
float PSP::mtot
Temporaries for stanza statistics.
std::string PSP::new_dir
SParticle PSP::part
Referenced by operator!=, operator++, operator==.
int PSP::pcount
std::vector< float > PSP::pmax
std::vector< float > PSP::pmed
std::vector< float > PSP::pmin
list<PSPstanza>::iterator PSP::spos
Referenced by GetNamed.
std::list<PSPstanza>::iterator PSP::spos
list<PSPstanza> PSP::stanzas
Referenced by GetNamed.
std::list<PSPstanza> PSP::stanzas
bool PSP::VERBOSE
std::vector< float > PSP::vmax
std::vector< float > PSP::vmed
std::vector< float > PSP::vmin
void PSP::check_dirname()
Append '/' if necessary.
Referenced by PSP.
void PSP::check_dirname()
Append '/' if necessary.
void PSP::ComputeStats()
void PSP::ComputeStats()
void PSP::init()
Stream init.
References in.
Referenced by PSP, PSP.
void PSP::init()
Stream init.
References in.
void PSP::write_binary(std::ostream &out, list< PSPstanza >::iterator its, bool real4)
void PSP::write_binary(std::ostream &out, std::list< PSPstanza >::iterator its, bool real4)
virtual SParticle * PSP::begin()
Define necessary member functions to be a valid container iterator
References GetParticle.
double PSP::CurrentTime()
Get snapshot time.
References header, MasterHeader::time.
double PSP::CurrentTime()
Get snapshot time.
References header, MasterHeader::time.
virtual SParticle * PSP::end()
virtual PSPstanza * PSP::GetNamed(const std::string &name)
Set stanza to name.
References cur, PSPstanza::name, spos, stanzas.
virtual PSPstanza * PSP::GetNamed(const std::string &name)
Set stanza to name.
References cur, PSPstanza::name, spos, stanzas.
virtual SParticle * PSP::GetParticle()=0
Reset to beginning of particles for this component.
Referenced by begin.
virtual SParticle * PSP::GetParticle()=0
Reset to beginning of particles for this component.
virtual PSPstanza * PSP::GetStanza()
Reset to beginning of stanza list and return null if no stanzas.
virtual PSPstanza * PSP::GetStanza()
Reset to beginning of stanza list and return null if no stanzas.
virtual SParticle * PSP::NextParticle()=0
Get next particle and return null at end.
Referenced by operator++.
virtual SParticle * PSP::NextParticle()=0
Get next particle and return null at end.
virtual PSPstanza * PSP::NextStanza()
Get next stanza in list and return null at end;.
virtual PSPstanza * PSP::NextStanza()
Get next stanza in list and return null at end;.
virtual bool PSP::operator!=(SParticle *const &other)
References part.
virtual SParticle * PSP::operator++()
References NextParticle, part.
virtual bool PSP::operator==(SParticle *const &other)
References part.
void PSP::PrintSummary(ostream &out, bool stats=false, bool timeonly=false)
Print summary phase-space info.
void PSP::PrintSummary(std::ostream &out, bool stats=false, bool timeonly=false)
Print summary phase-space info.
PSP::PSP(bool verbose)
Default constructor.
References init.
PSP::PSP(bool verbose)
Default constructor.
References init.
PSP::PSP(bool verbose, std::string new_dir)
Constructor specifying current working data directory.
References check_dirname, init.
PSP::PSP(bool verbose, std::string new_dir)
Constructor specifying current working data directory.
References check_dirname, init.
void PSP::writePSP(std::ostream &out, bool real4)
Write a new PSP file.
void PSP::writePSP(std::ostream &out, bool real4)
Write a new PSP file.
virtual PSP::~PSP()
Destructor.
References in.
virtual PSP::~PSP()
Destructor.
References in.
static std::shared_ptr< PSP > PSP::getPSP(const std::string &file, const std::string dir="", bool verbose=false)
PSP factory: choose type based on file name.