SphereSL
int SphereSL::lmax
int SphereSL::nmax
int SphereSL::numr
double SphereSL::rmax
Referenced by rb_max.
double SphereSL::rmin
Referenced by rb_min.
double SphereSL::scale
SLGridSph* SphereSL::slgrid
Referenced by rb_max, rb_min.
bool SphereSL::cache
int SphereSL::mpi
double SphereSL::d_r_to_rb(double const x)
double SphereSL::d_rb_to_r(const double x)
double SphereSL::dens(const int n, const int l, const double x)
void SphereSL::dens(const int n, const int l, const double x, Eigen::VectorXd &t)
double SphereSL::get_dens(const double r, const int l, const Eigen::VectorXd &coef)
double SphereSL::get_potl(const double r, const int l, const Eigen::VectorXd &coef)
double SphereSL::krnl(const int n, const int l)
double SphereSL::norm(const int n, const int l)
double SphereSL::potl(const int n, const int l, const double x)
Referenced by potlR, potlRZ.
void SphereSL::potl(const int n, const int l, const double x, Eigen::VectorXd &t)
double SphereSL::potlR(const int n, const int l, const double r)
References potl, r_to_rb.
double SphereSL::potlRZ(const int n, const int l, const double r, const double z)
References potl, r_to_rb.
double SphereSL::r_to_rb(double const r)
Referenced by potlR, potlRZ.
double SphereSL::rb_max(void)
References SLGridSph::r_to_xi, rmax, slgrid.
double SphereSL::rb_min(void)
References SLGridSph::r_to_xi, rmin, slgrid.
double SphereSL::rb_to_r(double const x)
SphereSL::SphereSL(int lmax, int nmax, int numr, double rmin, double rmax, double scale, std::shared_ptr< SphericalModelTable > mod)
SphereSL::~SphereSL(void)