BiorthGrid
std::vector<Eigen::MatrixXd> BiorthGrid::dens_grid
std::vector<Eigen::MatrixXd> BiorthGrid::dens_grid2
Eigen::MatrixXd BiorthGrid::krnl_grid
Referenced by krnl.
int BiorthGrid::lmax
int BiorthGrid::nmax
Eigen::MatrixXd BiorthGrid::norm_grid
Referenced by norm.
std::vector<Eigen::MatrixXd> BiorthGrid::potl_grid
std::vector<Eigen::MatrixXd> BiorthGrid::potl_grid2
double BiorthGrid::rmax
double BiorthGrid::rmin
int BiorthGrid::rnum
AxiSymBioPtr BiorthGrid::t
Referenced by d_r_to_rb, dens, potl, potlRZ, r_to_rb, rb_to_r.
Eigen::VectorXd BiorthGrid::x_grid
double BiorthGrid::xmax
Referenced by rb_max.
double BiorthGrid::xmin
Referenced by rb_min.
BiorthGrid::BiorthGrid(AxiSymBioPtr T, double RMIN=0.0, double RMAX=20, int NMAX=10, int LMAX=10, int RNUM=400)
double BiorthGrid::d_r_to_rb(double const r)
References t.
void BiorthGrid::dens(const int nn, const int l, const double r, Eigen::VectorXd &a)
References t.
double BiorthGrid::dens(const int nn, const int l, const double rb)
Referenced by densR.
double BiorthGrid::densR(const int nn, const int l, const double r)
References dens, r_to_rb.
double BiorthGrid::krnl(const int n, const int l)
References krnl_grid.
double BiorthGrid::norm(const int n, const int l)
References norm_grid.
void BiorthGrid::potl(const int nn, const int l, const double r, Eigen::VectorXd &a)
References t.
double BiorthGrid::potl(const int nn, const int l, const double rb)
Referenced by potlR.
double BiorthGrid::potlR(const int nn, const int l, const double r)
References potl, r_to_rb.
double BiorthGrid::potlRZ(const int nn, const int l, const double r, const double z)
References t.
double BiorthGrid::r_to_rb(double const r)
References t.
Referenced by densR, potlR.
double BiorthGrid::rb_max(void)
References xmax.
double BiorthGrid::rb_min(void)
References xmin.
double BiorthGrid::rb_to_r(double const rb)
References t.
virtual BiorthGrid::~BiorthGrid()