SphericalModelMulti
std::shared_ptr<AxiSymModel> SphericalModelMulti::fake
SphericalOrbit SphericalModelMulti::gen_orb
bool SphericalModelMulti::noneg
Referenced by allowNegativeMass.
SphericalOrbit SphericalModelMulti::orb
std::shared_ptr<AxiSymModel> SphericalModelMulti::real
Referenced by d2fde2, dfde, dfdl, distf, get_density, get_dpot, get_dpot2, get_mass, get_max_radius, get_min_radius, get_pot, get_pot_dpot.
double SphericalModelMulti::rmax_gen
Referenced by set_max_radius.
double SphericalModelMulti::rmin_gen
Referenced by set_min_radius.
void SphericalModelMulti::allowNegativeMass()
Turn off negative mass suppression by NOT requeueing particle selection if the DF ratio is negative
References noneg.
double SphericalModelMulti::d2fde2(double E, double L)
References real.
double SphericalModelMulti::dfde(double E, double L)
References real.
double SphericalModelMulti::dfdl(double E, double L)
References real.
double SphericalModelMulti::distf(double E, double L)
Evaluate distribution function and its partial derivatives.
References real.
Eigen::VectorXd SphericalModelMulti::gen_point(double Emin, double Emax, double Kmin, double Kmax, int &ierr)
Generate a phase-space point at a particular energy and angular momentum.
Eigen::VectorXd SphericalModelMulti::gen_point(double r, int &ierr)
Generate a phase-space point at a particular radius.
Eigen::VectorXd SphericalModelMulti::gen_point(int &ierr)
Overloaded to provide mass distribution from Real and Number distribution from Fake.
virtual double SphericalModelMulti::get_density(const double r)
References real.
Referenced by get_density.
double SphericalModelMulti::get_density(const double x1, const double x2, const double x3)
The density at (x, y, z)
References get_density.
virtual double SphericalModelMulti::get_dpot(const double r)
References real.
virtual double SphericalModelMulti::get_dpot2(const double r)
References real.
virtual double SphericalModelMulti::get_mass(const double r)
Evaluate the profile at a radial point.
References real.
Referenced by get_mass.
double SphericalModelMulti::get_mass(const double x1, const double x2, const double x3)
Get the mass inside of position (x, y, z) (this is ambiguous in general and will depend on the model)
References get_mass.
double SphericalModelMulti::get_max_radius(void)
References real.
double SphericalModelMulti::get_min_radius(void)
Additional member functions.
References real.
virtual double SphericalModelMulti::get_pot(const double r)
References real.
Referenced by get_pot.
double SphericalModelMulti::get_pot(const double x1, const double x2, const double x3)
The potential at (x, y, z)
References get_pot.
virtual void SphericalModelMulti::get_pot_dpot(const double r, double &p, double &dp)
References real.
void SphericalModelMulti::set_max_radius(const double &r)
References rmax_gen.
void SphericalModelMulti::set_min_radius(const double &r)
Set new minimum and maximum for realization.
References rmin_gen.
SphericalModelMulti::SphericalModelMulti(std::shared_ptr< AxiSymModel > Real, std::shared_ptr< AxiSymModel > Fake)
Constructor.