AxiSymModel
typedef vector<WRgrid> AxiSymModel::wrvector
double AxiSymModel::dEgrid
double AxiSymModel::dKgrid
vector<double> AxiSymModel::Egrid
vector<double> AxiSymModel::EgridMass
double AxiSymModel::Emax_grid
double AxiSymModel::Emin_grid
std::normal_distribution AxiSymModel::Gauss
double AxiSymModel::gen_ecut
Referenced by AxiSymModel, set_Ecut.
bool AxiSymModel::gen_firstime
Referenced by AxiSymModel.
bool AxiSymModel::gen_firstime_E
Referenced by AxiSymModel.
bool AxiSymModel::gen_firstime_jeans
Referenced by AxiSymModel.
Eigen::VectorXd AxiSymModel::gen_fmax
double AxiSymModel::gen_fomax
Eigen::VectorXd AxiSymModel::gen_mass
SphericalOrbit AxiSymModel::gen_orb
Eigen::VectorXd AxiSymModel::gen_rloc
vector<double> AxiSymModel::Jmax
vector<double> AxiSymModel::Kgrid
vector<wrvector> AxiSymModel::Rgrid
std::uniform_real_distribution AxiSymModel::Unit
Stuff for gen_point.
int AxiSymModel::gen_E
bool AxiSymModel::gen_EJ
Stuff for gen_point.
int AxiSymModel::gen_itmax
Referenced by set_itmax.
int AxiSymModel::gen_K
double AxiSymModel::gen_kmin
int AxiSymModel::gen_logr
int AxiSymModel::gen_N
double AxiSymModel::gen_rmin
double AxiSymModel::gen_tolE
double AxiSymModel::gen_tolK
int AxiSymModel::numj
int AxiSymModel::numr
bool AxiSymModel::dist_defined
The distribution is defined and computed.
Referenced by CylDisk::CylDisk, DiskWithHalo::DiskWithHalo, DiskWithHalo::DiskWithHalo, ExponentialDisk::ExponentialDisk, HernquistSphere::HernquistSphere, PlummerSphere::PlummerSphere, SingIsothermalSphere::SingIsothermalSphere, ToomreDisk::ToomreDisk, ZangDisk::ZangDisk.
Eigen::VectorXd AxiSymModel::gen_point_2d(double r, int &ierr)
Eigen::VectorXd AxiSymModel::gen_point_2d(int &ierr)
Referenced by gen_point, gen_point.
Eigen::VectorXd AxiSymModel::gen_point_3d(double Emin, double Emax, double Kmin, double Kmax, int &ierr)
Eigen::VectorXd AxiSymModel::gen_point_3d(int &ierr)
Referenced by gen_point, gen_point.
Eigen::VectorXd AxiSymModel::gen_point_jeans_3d(int &ierr)
Referenced by gen_point_jeans.
AxiSymModel::AxiSymModel(void)
Constructor.
References gen_ecut, gen_firstime, gen_firstime_E, gen_firstime_jeans, MassModel::ModelID.
virtual double AxiSymModel::d2fde2(double, double)=0
virtual double AxiSymModel::dfde(double, double)=0
virtual double AxiSymModel::dfdl(double, double)=0
virtual double AxiSymModel::distf(double, double)=0
virtual Eigen::VectorXd AxiSymModel::gen_point(double Emin, double Emax, double Kmin, double Kmax, int &ierr)
Generate a phase-space point at a particular energy and angular momentum.
References MassModel::bomb, MassModel::dof, gen_point_3d.
virtual Eigen::VectorXd AxiSymModel::gen_point(double r, int &ierr)
Generate a phase-space point at a particular radius.
References MassModel::bomb, MassModel::dof, gen_point_2d.
virtual Eigen::VectorXd AxiSymModel::gen_point(int &ierr)
Generate a phase-space point.
References MassModel::bomb, MassModel::dof, gen_point_2d, gen_point_3d.
virtual Eigen::VectorXd AxiSymModel::gen_point_jeans(int &ierr)
Generate a phase-space point using Jeans' equations.
References MassModel::bomb, MassModel::dof, gen_point_jeans_3d.
virtual void AxiSymModel::gen_velocity(double *pos, double *vel, int &ierr)
Generate a the velocity variate from a position.
double AxiSymModel::get_density(const double x1, const double x2, const double x3) override
The density at (x, y, z)
References get_density.
virtual double AxiSymModel::get_density(const double)=0
Referenced by get_density.
virtual double AxiSymModel::get_dpot(const double)=0
virtual double AxiSymModel::get_dpot2(const double)=0
double AxiSymModel::get_mass(const double x1, const double x2, const double x3) override
Get the mass inside of position (x, y, z) (this is ambiguous in general and will depend on the model)
References get_mass.
virtual double AxiSymModel::get_mass(const double)=0
Access the profile.
Referenced by get_mass.
virtual double AxiSymModel::get_max_radius(void)=0
virtual double AxiSymModel::get_min_radius(void)=0
double AxiSymModel::get_pot(const double x1, const double x2, const double x3) override
The potential at (x, y, z)
References get_pot.
virtual double AxiSymModel::get_pot(const double)=0
Referenced by get_pot.
virtual void AxiSymModel::get_pot_dpot(const double, double &, double &)=0
void AxiSymModel::set_Ecut(double cut)
Set cutoff on multimass realization grid.
References gen_ecut.
void AxiSymModel::set_itmax(int s)
Maximum number of iterations for obtaining a valid variate.
References gen_itmax.
virtual AxiSymModel::~AxiSymModel()
Destructor.