SParticle
std::shared_ptr< PParticle< double > > SParticle::d
Referenced by datr, iatr, indx, mass, ndatr, niatr, phi, pos, read, read, setSize, vel.
std::shared_ptr< PParticle< float > > SParticle::f
Referenced by datr, iatr, indx, mass, ndatr, niatr, phi, pos, read, read, setSize, vel.
double SParticle::mass
Data fields.
Referenced by cpy.
double SParticle::pos[3][3]
Referenced by cpy.
double SParticle::vel[3][3]
Referenced by cpy.
unsigned SParticle::s
Referenced by read, read, setSize.
void SParticle::cpy(const Particle &p)
Copy Particle contents.
References Particle::mass, mass, Particle::pos, pos, Particle::vel, vel.
Referenced by operator[], SParticle.
double SParticle::datr(int i)
References d, datr, f.
Referenced by datr.
double SParticle::datr(int i)
References d, datr, f.
int SParticle::iatr(int i)
References d, f, iatr.
Referenced by iatr.
int SParticle::iatr(int i)
References d, f, iatr.
int SParticle::indx()
References d, f.
int SParticle::indx()
References d, f.
double SParticle::mass()
References d, f.
double SParticle::mass()
References d, f.
int SParticle::ndatr()
References d, f.
int SParticle::ndatr()
References d, f.
int SParticle::niatr()
References d, f.
int SParticle::niatr()
References d, f.
void SParticle::operator[](const Particle &p)
Copy contents of a Particle to an SParticle.
References cpy.
double SParticle::phi()
References d, f.
double SParticle::phi()
References d, f.
double SParticle::pos(int i)
References d, f.
double SParticle::pos(int i)
References d, f.
void SParticle::read(std::istream &in, unsigned rsize, int pcount, list< PSPstanza >::iterator spos)
References d, f, s, setSize.
void SParticle::read(std::istream &in, unsigned rsize, int pcount, std::list< PSPstanza >::iterator spos)
References d, f, s, setSize.
void SParticle::setSize(unsigned rsize)
References d, f, s.
Referenced by read, read.
void SParticle::setSize(unsigned rsize)
References d, f, s.
SParticle::SParticle()
SParticle::SParticle()
Null constructor.
SParticle::SParticle()
SParticle::SParticle(const Particle &p)
Construct instance from a Particle.
References cpy.
double SParticle::vel(int i)
References d, f.
double SParticle::vel(int i)
References d, f.
void SParticle::write(std::ostream &out, bool real4, size_t isiz)
void SParticle::write(std::ostream &out, bool real4, size_t isiz)