Sech2Halo
double Sech2Halo::dispx
Referenced by dfde, dfdv, distf, Sech2Halo.
double Sech2Halo::dispz
Referenced by dfde, dfdv, distf, Sech2Halo.
double Sech2Halo::dratio
Referenced by Sech2Halo.
double Sech2Halo::h
Referenced by get_max_radius, get_scale_height.
double Sech2Halo::hh
Referenced by get_dpot, get_dpot2, get_pot, get_pot_dpot, get_scale_height_halo.
double Sech2Halo::hmax
Referenced by get_max_radius, set_hmax.
double Sech2Halo::hratio
Referenced by Sech2Halo.
bool Sech2Halo::model_computed
Referenced by dfde, dfdv, distf, get_dpot, get_dpot2, get_pot, get_pot_dpot, Sech2Halo.
double Sech2Halo::norm
Referenced by dfde, dfdv, distf.
double Sech2Halo::rho0
Referenced by get_rho0.
double Sech2Halo::rho0h
Referenced by get_dpot, get_dpot2, get_pot, get_pot_dpot, get_rho0_halo.
double Sech2Halo::HMAX
Referenced by set_hmax.
bool Sech2Halo::MU
int Sech2Halo::NTABLE
double Sech2Halo::OFFSET
void Sech2Halo::reset()
Referenced by dfde, dfdv, distf, get_dpot, get_dpot2, get_pot, get_pot_dpot.
double Sech2Halo::dfde(const double E, const double p=0.0)
References dispx, dispz, model_computed, norm, reset.
double Sech2Halo::dfdv(const double E, const double p=0.0)
References dispx, dispz, model_computed, norm, reset.
double Sech2Halo::distf(const double E, const double p=0.0)
References dispx, dispz, model_computed, norm, reset.
double Sech2Halo::get_dpot(const double z)
References OneDModelTable::get_dpot, hh, model_computed, reset, rho0h.
double Sech2Halo::get_dpot2(const double z)
References OneDModelTable::get_dpot2, hh, model_computed, reset, rho0h.
double Sech2Halo::get_max_radius(void)
References h, hmax.
double Sech2Halo::get_min_radius(void)
double Sech2Halo::get_pot(const double z)
References OneDModelTable::get_pot, hh, model_computed, reset, rho0h.
std::tuple< double, double > Sech2Halo::get_pot_dpot(const double z)
References OneDModelTable::get_pot_dpot, hh, model_computed, reset, rho0h.
double Sech2Halo::get_rho0(void)
References rho0.
double Sech2Halo::get_rho0_halo(void)
References rho0h.
double Sech2Halo::get_scale_height(void)
References h.
double Sech2Halo::get_scale_height_halo(void)
References hh.
Sech2Halo::Sech2Halo(const double DISPZ, const double DRATIO, const double HRATIO, const double DISPX=1.0)
Sech2Halo::Sech2Halo(void)
References dispx, dispz, OneDModel::dist_defined, dratio, hratio, model_computed.
static void Sech2Halo::set_hmax(double hmax)
References hmax, HMAX.