MassModel
bool MassModel::defined
True if model is assigned.
int MassModel::dim
The number of dimensions (degrees of freedom)
Referenced by CylDisk::CylDisk, DiskWithHalo::DiskWithHalo, DiskWithHalo::DiskWithHalo, dof, ExponentialDisk::ExponentialDisk, HernquistSphere::HernquistSphere, KalnajsDisk::KalnajsDisk, PlummerSphere::PlummerSphere, SingIsothermalSphere::SingIsothermalSphere, ToomreDisk::ToomreDisk, ZangDisk::ZangDisk.
string MassModel::ModelID
Model identifier.
Referenced by AxiSymModel::AxiSymModel, bomb, CylDisk::CylDisk, DiskWithHalo::DiskWithHalo, DiskWithHalo::DiskWithHalo, ExponentialDisk::ExponentialDisk, HernquistSphere::HernquistSphere, KalnajsDisk::KalnajsDisk, KingSphere::KingSphere, PlummerSphere::PlummerSphere, SingIsothermalSphere::SingIsothermalSphere, ToomreDisk::ToomreDisk, ZangDisk::ZangDisk.
void MassModel::bomb(const char *s)
Exception handling using std::exception.
References ModelID.
Referenced by ExponentialDisk::d2fde2, HunterDisk::d2fde2, HunterDiskX::d2fde2, CylDisk::d2fde2, DiskWithHalo::d2fde2, ExponentialDisk::dfde, HunterDisk::dfde, HunterDiskX::dfde, CylDisk::dfde, DiskWithHalo::dfde, ExponentialDisk::dfdl, HunterDisk::dfdl, HunterDiskX::dfdl, CylDisk::dfdl, DiskWithHalo::dfdl, ExponentialDisk::distf, HunterDisk::distf, HunterDiskX::distf, CylDisk::distf, DiskWithHalo::distf, AxiSymModel::gen_point, AxiSymModel::gen_point, AxiSymModel::gen_point, AxiSymModel::gen_point_jeans, HernquistSphere::get_density, SingIsothermalSphere::get_density, IsothermalSphere::get_density, LowSingIsothermalSphere::get_density, ZangDisk::get_density, SingIsothermalSphere::get_dpot, IsothermalSphere::get_dpot, LowSingIsothermalSphere::get_dpot, ZangDisk::get_dpot, SingIsothermalSphere::get_dpot2, IsothermalSphere::get_dpot2, LowSingIsothermalSphere::get_dpot2, ZangDisk::get_dpot2, SingIsothermalSphere::get_mass, IsothermalSphere::get_mass, LowSingIsothermalSphere::get_mass, ZangDisk::get_mass, SingIsothermalSphere::get_pot, IsothermalSphere::get_pot, LowSingIsothermalSphere::get_pot, ZangDisk::get_pot, SingIsothermalSphere::get_pot_dpot, IsothermalSphere::get_pot_dpot, LowSingIsothermalSphere::get_pot_dpot, ZangDisk::get_pot_dpot, KalnajsDisk::setup_df, KingSphere::setup_df.
int MassModel::dof()
Return the number of dimensions (degrees of freedom)
References dim.
Referenced by AxiSymModel::gen_point, AxiSymModel::gen_point, AxiSymModel::gen_point, AxiSymModel::gen_point_jeans.
virtual double MassModel::get_density(const double, const double, const double)=0
The density at (x, y, z)
virtual double MassModel::get_mass(const double, const double, const double)=0
Get the mass inside of position (x, y, z) (this is ambiguous in general and will depend on the model)
virtual double MassModel::get_pot(const double, const double, const double)=0
The potential at (x, y, z)
virtual MassModel::~MassModel()
Destructor.