KDtree::point
std::array<coordinate_type, dimensions> KDtree::point< coordinate_type, dimensions >::coords_
Referenced by KDtree::point< coordinate_type, dimensions >::get, KDtree::point< coordinate_type, dimensions >::point, KDtree::point< coordinate_type, dimensions >::point, KDtree::point< coordinate_type, dimensions >::point.
unsigned long KDtree::point< coordinate_type, dimensions >::indx_
Referenced by KDtree::point< coordinate_type, dimensions >::indx, KDtree::point< coordinate_type, dimensions >::point.
double KDtree::point< coordinate_type, dimensions >::mass_
Referenced by KDtree::point< coordinate_type, dimensions >::mass, KDtree::point< coordinate_type, dimensions >::point.
std::array<coordinate_type, dimensions> KDtree::point< coordinate_type, dimensions >::vels_
Referenced by KDtree::point< coordinate_type, dimensions >::point, KDtree::point< coordinate_type, dimensions >::point, KDtree::point< coordinate_type, dimensions >::vel.
double KDtree::point< coordinate_type, dimensions >::distance(const point &pt) const
Returns the distance squared from this point to another point. pt another point distance squared from this point to the other point
References KDtree::point< coordinate_type, dimensions >::get.
Referenced by KDtree::kdtree< coordinate_type, dimensions >::node::distance.
coordinate_type KDtree::point< coordinate_type, dimensions >::get(size_t index) const
Returns the coordinate in the given dimension. index dimension index (zero based) coordinate in the given dimension
References KDtree::point< coordinate_type, dimensions >::coords_.
Referenced by KDtree::point< coordinate_type, dimensions >::distance, KDtree::kdtree< coordinate_type, dimensions >::node::get, KDtree::kdtree< coordinate_type, dimensions >::nearestN, KDtree::kdtree< coordinate_type, dimensions >::node_cmp::operator(), KDtree::operator<<.
unsigned long KDtree::point< coordinate_type, dimensions >::indx() const
References KDtree::point< coordinate_type, dimensions >::indx_.
Referenced by KDtree::kdtree< coordinate_type, dimensions >::accum, KDtree::kdtree< coordinate_type, dimensions >::walk.
double KDtree::point< coordinate_type, dimensions >::mass() const
References KDtree::point< coordinate_type, dimensions >::mass_.
KDtree::point< coordinate_type, dimensions >::point()
Null initializer.
KDtree::point< coordinate_type, dimensions >::point(const point &p)
Copy constructor.
References KDtree::point< coordinate_type, dimensions >::coords_, KDtree::point< coordinate_type, dimensions >::indx_, KDtree::point< coordinate_type, dimensions >::mass_, KDtree::point< coordinate_type, dimensions >::vels_.
KDtree::point< coordinate_type, dimensions >::point(std::array< coordinate_type, dimensions > c, double m=1, unsigned long indx=0)
Constructor.
KDtree::point< coordinate_type, dimensions >::point(std::array< coordinate_type, dimensions > c, std::array< coordinate_type, dimensions > v, double m=1, unsigned long indx=0)
KDtree::point< coordinate_type, dimensions >::point(std::initializer_list< coordinate_type > list, double m=1, unsigned long indx=0)
List constructor.
References KDtree::point< coordinate_type, dimensions >::coords_.
KDtree::point< coordinate_type, dimensions >::point(std::initializer_list< coordinate_type > list, std::initializer_list< coordinate_type > vlst, double m=1, unsigned long indx=0)
References KDtree::point< coordinate_type, dimensions >::coords_, KDtree::point< coordinate_type, dimensions >::vels_.
double KDtree::point< coordinate_type, dimensions >::speed(const point &pt) const
Returns the squared velocity between this point to another point. pt another point squared speed between this point and the other point
References KDtree::point< coordinate_type, dimensions >::vel.
coordinate_type KDtree::point< coordinate_type, dimensions >::vel(size_t index) const
References KDtree::point< coordinate_type, dimensions >::vels_.
Referenced by KDtree::point< coordinate_type, dimensions >::speed.