SphericalModelTable
RUN SphericalModelTable::density
FDIST SphericalModelTable::df
Referenced by get_ra2.
FDISTC SphericalModelTable::dfc
int SphericalModelTable::diverge
double SphericalModelTable::diverge_rfac
int SphericalModelTable::external
double SphericalModelTable::foffset
RUN SphericalModelTable::mass
Referenced by get_max_radius, get_min_radius.
int SphericalModelTable::num
Referenced by grid_size.
int SphericalModelTable::num_params
Referenced by get_num_param.
int SphericalModelTable::numdf
std::vector<double> SphericalModelTable::params
Referenced by get_param.
RUN SphericalModelTable::pot
int SphericalModelTable::chebyN
Chebyshev order (default: 0, no Chebyshev)
int SphericalModelTable::count
Count the number of instantiations (for debugging)
int SphericalModelTable::even
Assume even spacing in the mass model table (default: yes)
int SphericalModelTable::linear
Linear interpolation in model (default: no)
void SphericalModelTable::debug_fdist()
double SphericalModelTable::d2fde2(double E, double L)
double SphericalModelTable::dfde(double E, double L)
double SphericalModelTable::dfdl(double E, double L)
double SphericalModelTable::distf(double E, double L)
Evaluate the distribution function.
double SphericalModelTable::get_density(const double x1, const double x2, const double x3)
The density at (x, y, z)
References get_density.
virtual double SphericalModelTable::get_density(const double)
Referenced by get_density.
virtual double SphericalModelTable::get_dpot(const double)
virtual double SphericalModelTable::get_dpot2(const double)
double SphericalModelTable::get_mass(const double x1, const double x2, const double x3)
Get the mass inside of position (x, y, z) (this is ambiguous in general and will depend on the model)
References get_mass.
virtual double SphericalModelTable::get_mass(const double)
Evaluate the profile at a particular radius.
Referenced by get_mass.
double SphericalModelTable::get_max_radius(void)
References mass, RUN::num, RUN::x.
double SphericalModelTable::get_min_radius(void)
References mass, RUN::x.
int SphericalModelTable::get_num_param(void)
Get info about the model.
References num_params.
Referenced by KingSphere::setup_df.
double SphericalModelTable::get_param(int i)
References params.
Referenced by KingSphere::setup_df.
double SphericalModelTable::get_pot(const double x1, const double x2, const double x3)
The potential at (x, y, z)
References get_pot.
virtual double SphericalModelTable::get_pot(const double)
Referenced by get_pot.
virtual void SphericalModelTable::get_pot_dpot(const double, double &, double &)
double SphericalModelTable::get_ra2(void)
References df, FDIST::ra2.
int SphericalModelTable::grid_size(void)
References num.
void SphericalModelTable::print_df(const std::string &name)
void SphericalModelTable::print_model(const std::string &name)
void SphericalModelTable::print_model_eval(const std::string &name, int number)
void SphericalModelTable::setup_df(int NUM, double RA=1.0e20)
Set up and get info about the phase-space distribution.
SphericalModelTable::SphericalModelTable(int num, double *r, double *d, double *m, double *p, int DIVERGE=0, double DIVERGE_RFAC=0, int EXTERNAL=0, std::string ID="")
Constructor (from array pointers)
SphericalModelTable::SphericalModelTable(std::vector< double > &r, std::vector< double > &d, std::vector< double > &m, std::vector< double > &p, int DIVERGE=0, double DIVERGE_RFAC=0, int EXTERNAL=0, std::string ID="")
Constructor (from vectors)
SphericalModelTable::SphericalModelTable(string filename, int DIVERGE=0, double DIVERGE_RFAC=1.0, int EXTERNAL=0)
Constructor (from a table)
virtual SphericalModelTable::~SphericalModelTable()
Destructor.