SphericalOrbit
double SphericalOrbit::am
struct ANGLE_GRID SphericalOrbit::angle_grid
Referenced by get_angle_grid.
double SphericalOrbit::ap
double SphericalOrbit::beta
Referenced by Beta.
std::shared_ptr<AxiSymBiorth> SphericalOrbit::biorth
Referenced by orth, set_biorth.
Eigen::VectorXd SphericalOrbit::cosvec
double SphericalOrbit::energy
Referenced by Energy.
GaussQuad SphericalOrbit::Gkn
double SphericalOrbit::jmax
Referenced by AngMom, Jmax.
double SphericalOrbit::kappa
Referenced by AngMom, Kappa.
int SphericalOrbit::l
Referenced by set_biorth.
int SphericalOrbit::l1s
int SphericalOrbit::l2s
std::shared_ptr<AxiSymModel> SphericalOrbit::model
Referenced by modl.
int SphericalOrbit::nbsct
Referenced by set_numerical_params.
int SphericalOrbit::nmax
Referenced by set_biorth, set_numerical_params.
double SphericalOrbit::r_apo
Referenced by apo.
double SphericalOrbit::r_circ
Referenced by circ.
double SphericalOrbit::r_peri
Referenced by peri.
int SphericalOrbit::recs
Referenced by set_numerical_params.
int SphericalOrbit::RECUR
Referenced by set_biorth.
double SphericalOrbit::sm
double SphericalOrbit::sp
bool SphericalOrbit::guard
int SphericalOrbit::Nseg
double SphericalOrbit::RMAXF
double SphericalOrbit::tol
double SphericalOrbit::tolnr
double SphericalOrbit::ZFRAC
void SphericalOrbit::compute_action(void)
References compute_freq.
Referenced by get_action.
void SphericalOrbit::compute_angles(void)
Referenced by get_angle_grid.
void SphericalOrbit::compute_angles_epi(void)
void SphericalOrbit::compute_angles_old(void)
void SphericalOrbit::compute_biorth(void)
void SphericalOrbit::compute_freq(void)
Referenced by AngMom, apo, circ, compute_action, get_angle_grid, get_freq, Jmax, peri.
void SphericalOrbit::compute_freq_epi(void)
std::tuple< double, double, bool > SphericalOrbit::search(std::function< double(double)> func, double rmin, double rmax)
double SphericalOrbit::AngMom(void)
The value of the orbital angular momentum.
References compute_freq, RegularOrbit::freq_defined, jmax, kappa.
double SphericalOrbit::apo(void)
Radius of the apocenter of this orbit.
References compute_freq, RegularOrbit::freq_defined, r_apo.
double SphericalOrbit::Beta(void)
The specified altitude of the orbital plane.
References beta.
double SphericalOrbit::circ(void)
Radius of the circular orbit with energy E.
References compute_freq, RegularOrbit::freq_defined, r_circ.
double SphericalOrbit::Energy(void)
Safe access to internal quantities.
The value of the orbital energy
References energy.
double SphericalOrbit::get_action(const int i)
Required functions for accessing phase-space parameters.
Return the action where: index 0 is radial action, I_r index 1 is angular action, J index 2 should be J_z/J, current set to zero
References RegularOrbit::action, RegularOrbit::action_defined, RegularOrbit::bomb, compute_action, RegularOrbit::dof.
double SphericalOrbit::get_angle(const int i, const double time)
Get angle dependent quantities for the orbit where the index signifies: i val 1 w1 2 w2 3 t 4 dw1dt 5 f 6 r 7 phi
struct ANGLE_GRID * SphericalOrbit::get_angle_grid(void)
Access to underlying grid for pot_trans.
References RegularOrbit::angle_defined, angle_grid, compute_angles, compute_freq, RegularOrbit::freq_defined.
double SphericalOrbit::get_freq(const int i)
Return the orbital frequency where: index 0 is radial frequency, I_r index 1 is angular frequency, J index 2 is frequency of line of nodes (zero for a spherical system)
References RegularOrbit::bomb, compute_freq, RegularOrbit::dof, RegularOrbit::freq, RegularOrbit::freq_defined.
double SphericalOrbit::get_w1(double r, double vr)
Get radial angle for a given radius.
double SphericalOrbit::Jmax(void)
The value of the current J_{max}(E)
References compute_freq, RegularOrbit::freq_defined, jmax.
double SphericalOrbit::Kappa(void)
The value of the current J/J_{max}(E)
References kappa.
AxiSymModel & SphericalOrbit::modl(void)
Get the underlying axisymmetric model object.
References model.
void SphericalOrbit::new_orbit(double Energy, double kappa, double beta=0.0)
Set the energy and kappa for the orbit.
SphericalOrbit & SphericalOrbit::operator=(const SphericalOrbit &)
AxiSymBiorth & SphericalOrbit::orth(void)
Get the underlying biorthogonal function object.
References biorth.
double SphericalOrbit::peri(void)
Radius of the pericenter of this orbit.
References compute_freq, RegularOrbit::freq_defined, r_peri.
void SphericalOrbit::pot_trans(int l1, int l2, Eigen::VectorXd &t)
double SphericalOrbit::pot_trans(int l1, int l2, int n)
double SphericalOrbit::pot_trans(int l1, int l2, std::function< double(double)> func)
void SphericalOrbit::set_biorth(std::shared_ptr< AxiSymBiorth > type, int ll, int max, int recur=0)
Set the biorthogonal ffunction type.
References biorth, RegularOrbit::biorth_defined, l, nmax, RECUR.
void SphericalOrbit::set_numerical_params(int RECS=64, int NMAX=40, int NBSCT=3)
Set the numerical parameters for angle transform computation.
References nbsct, nmax, recs.
SphericalOrbit::SphericalOrbit(const SphericalOrbit &)
SphericalOrbit::SphericalOrbit(std::shared_ptr< AxiSymModel > model)
SphericalOrbit::SphericalOrbit(std::shared_ptr< AxiSymModel > model, double Energy, double kappa, double beta=0.0)
SphericalOrbit::SphericalOrbit(void)
virtual SphericalOrbit::~SphericalOrbit()