Sech2
double Sech2::dispx
Referenced by dfde, dfdv, distf, Sech2, Sech2.
double Sech2::dispz
Referenced by dfde, dfdv, distf, Sech2, Sech2.
double Sech2::h
Referenced by get_density, get_dpot, get_dpot2, get_mass, get_max_radius, get_pot, get_pot_dpot, get_scale_height, Sech2, Sech2.
double Sech2::norm
Referenced by dfde, dfdv, distf, Sech2, Sech2.
double Sech2::HMAX
Referenced by get_max_radius, set_hmax.
double Sech2::dfde(const double E, const double p)
References dispx, dispz, norm.
double Sech2::dfdv(const double E, const double p)
References dispx, dispz, norm.
double Sech2::distf(const double E, const double p)
References dispx, dispz, norm.
double Sech2::get_density(const double x, const double y, const double z)
The density at (x, y, z)
References get_density.
double Sech2::get_density(const double z)
References h.
Referenced by get_density.
double Sech2::get_dpot(const double z)
References h.
double Sech2::get_dpot2(const double z)
References h.
double Sech2::get_mass(const double x, const double y, const double z)
Get the mass inside of position (x, y, z) (this is ambiguous in general and will depend on the model)
References get_mass.
double Sech2::get_mass(const double z)
References h.
Referenced by get_mass.
double Sech2::get_max_radius(void)
References h, HMAX.
double Sech2::get_min_radius(void)
double Sech2::get_pot(const double x, const double y, const double z)
The potential at (x, y, z)
References get_pot.
double Sech2::get_pot(const double z)
References h.
Referenced by get_pot.
tuple< double, double > Sech2::get_pot_dpot(const double z)
References h.
double Sech2::get_scale_height(void)
References h.
Sech2::Sech2(const double DISPZ, const double DISPX=1.0)
References dispx, dispz, OneDModel::dist_defined, h, norm.
Sech2::Sech2(void)
References dispx, dispz, OneDModel::dist_defined, h, norm.
static void Sech2::set_hmax(double hmax)
References HMAX.