EmbeddedDiskModel
std::shared_ptr<QPDistF> EmbeddedDiskModel::df
std::vector<double> EmbeddedDiskModel::m_scale
int EmbeddedDiskModel::number
std::vector<double> EmbeddedDiskModel::r_scale
double EmbeddedDiskModel::rmax
Referenced by get_max_radius.
double EmbeddedDiskModel::rmin
Referenced by get_min_radius.
std::vector<std::shared_ptr<AxiSymModel> > EmbeddedDiskModel::t
double EmbeddedDiskModel::d2fde2(double E, double L)
double EmbeddedDiskModel::dfde(double E, double L)
double EmbeddedDiskModel::dfdl(double E, double L)
double EmbeddedDiskModel::distf(double E, double L)
EmbeddedDiskModel::EmbeddedDiskModel(std::vector< std::shared_ptr< AxiSymModel > > &T, std::vector< double > &M_scale, std::vector< double > &R_scale, int NUMBER)
double EmbeddedDiskModel::get_density(const double x1, const double x2, const double x3)
The density at (x, y, z)
References get_density.
virtual double EmbeddedDiskModel::get_density(const double)
Referenced by get_density.
virtual double EmbeddedDiskModel::get_dpot(const double)
virtual double EmbeddedDiskModel::get_dpot2(const double)
double EmbeddedDiskModel::get_mass(const double x1, const double x2, const double x3)
Get the mass inside of position (x, y, z) (this is ambiguous in general and will depend on the model)
References get_mass.
virtual double EmbeddedDiskModel::get_mass(const double)
Access the profile.
Referenced by get_mass.
double EmbeddedDiskModel::get_max_radius(void)
References rmax.
double EmbeddedDiskModel::get_min_radius(void)
References rmin.
double EmbeddedDiskModel::get_pot(const double x1, const double x2, const double x3)
The potential at (x, y, z)
References get_pot.
virtual double EmbeddedDiskModel::get_pot(const double)
Referenced by get_pot.
virtual void EmbeddedDiskModel::get_pot_dpot(const double, double &, double &)
void EmbeddedDiskModel::save_df(string &file)
void EmbeddedDiskModel::setup_df(int egrid=10, int kgrid=5, int mgrid=20, double lambda=0.0, double alpha=-6.0, double beta=1.0, double gama=1.0, double sigma=2.0, double rmmax=-1, double roff=0.05, double eoff=0.5, double koff=0.5, double kmin=0.0, double kmax=1.0, int nint=20, int numt=20)
void EmbeddedDiskModel::setup_df(string &file)
void EmbeddedDiskModel::verbose_df(void)
virtual EmbeddedDiskModel::~EmbeddedDiskModel()