expand.H
BSD_SOURCE
Description: This routine is an NBODY code whose force calculation is based on a biorthogonal phase-space expansion; for now, the expansion set is based on the eigenfunctions of the spherical Laplacian: Y_{lm} * j_n ^ ^ | | | spherical Bessel functions | spherical harmonics Call sequence: exp [-f parameter file] [ [keyword=value] [keyword=value] ... ] Parameters: The parameter file may be used instead of the keyword/value pairs. The available keywords are: KEYWORD EXPLANATION DEFAULT lmax = maximum harmonic order 4 nmax = maximum radial order 18 nlog = interval between log output 10 nlist = interval between p-s output 50 nsteps = total number of steps to run 500 fixacc = add off set to acceleration to conserve momentum 1 (1=yes 0=no) selfgrav = turn-on self-gravity 1 outbods = output phase space 1 outengy = output per particle energies 0 diag = diagnostic output 0 dtime = time step 0.1 rmax = maximum radial extent (computed from input) logfile = logfile name LOG.FILE infile = input parameter file IN.FILE outname = output file prefix OUT parmfile = parameter file name PARMS.FILE $Id$
MAX
MIN
const double DSMALL
const int mdtDim
void adjust_multistep_level()
double atof(string &s)
References atof.
Referenced by atof.
int atoi(string &s)
References atoi.
Referenced by atoi, atol, PotAccel::atol.
bool atol(string &s)
References atoi.
void begin_run(void)
void create_tipsy(void)
double densi(double rr, int l, int n)
double dgammln()
void do_output_init(void)
double dplgndr(int l, int m, double x)
void exp_mpi_error_handler(MPI_Comm *communicator, int *error_code,...)
double factrl(int n)
double get_dens(double r, int l, double *coef)
void get_potacc(double r, int l, double *coef, double *p, double *dp)
void get_ultra(int nmax, double l, double x, Eigen::VectorXd &p)
void incr_com_position(double dt)
void incr_com_velocity(double dt)
void incr_position(double dt, int mlevel=0)
void incr_velocity(double dt, int mlevel=0)
void init_velocity(void)
void initialize_cuda(void)
void initialize_multistep()
void locate()
void make_grid(double rmin, double rmax, int lmax, int nmax)
void mpi_gdb_print_trace(int sig)
void mpi_gdb_wait_trace(int sig)
void mpi_print_trace(const string &routine, const string &msg, const char *file, int line)
double MPL_read_timer(int reset)
void MPL_reset_timer(void)
void MPL_start_timer(void)
void MPL_stop_timer(void)
void parallel_distribute_coefficients(void)
void parallel_gather_coefficients(void)
double plgndr(int, int, double)
double potli(double rr, int l, int n)
void print_trace(std::ostream &out, const char *file, int line)
void recompute_processor_rates(void)
void redistribute_particles(void)
void set_fpu_gdb_handler(void)
void set_fpu_invalid_handler(void)
void set_fpu_trace_handler(void)
void set_global_com(void)
void setup_distribution(void)
void signal_handler_dump(int sig)
void signal_handler_stop(int sig)
void sync_eval_multistep()
void test_mpi(void)
string trimComment(const string)
string trimLeft(const string)
string trimRight(const string)
void write_parm(void)
double zbrent()