interp.H
double drv2(double x, const V &xtab, const V &ftab, int even=0)
Referenced by CylDisk::get_dpot, CylDisk::get_pot_dpot.
double odd2(double x, const V &xtab, const V &ftab, int even=0)
Referenced by CylDisk::get_density, CylDisk::get_mass, CylDisk::get_pot.
void Spline(const Eigen::VectorXd &x, const Eigen::VectorXd &y, double yp1, double ypn, Eigen::VectorXd &y2)
void Splint1(const Eigen::VectorXd &xa, const Eigen::VectorXd &ya, const Eigen::VectorXd &y2a, double x, double &y, int even=0)
Referenced by IsothermalSphere::get_density, LowSingIsothermalSphere::get_density, IsothermalSphere::get_dpot, LowSingIsothermalSphere::get_dpot, IsothermalSphere::get_dpot2, LowSingIsothermalSphere::get_dpot2, IsothermalSphere::get_mass, LowSingIsothermalSphere::get_mass, IsothermalSphere::get_pot, LowSingIsothermalSphere::get_pot, IsothermalSphere::get_pot_dpot, LowSingIsothermalSphere::get_pot_dpot.
void Splint2(const Eigen::VectorXd &xa, const Eigen::VectorXd &ya, const Eigen::VectorXd &y2a, double x, double &y, double &dy, int even=0)
void Splint3(const Eigen::VectorXd &xa, const Eigen::VectorXd &ya, const Eigen::VectorXd &y2a, double x, double &y, double &dy, double &dyy, int even=0)
double Splsum(const Eigen::VectorXd &x, const Eigen::VectorXd &y)
void Splsum(const Eigen::VectorXd &x, const Eigen::VectorXd &y, Eigen::VectorXd &z)
double Trapsum(const Eigen::VectorXd &x, const Eigen::VectorXd &y)
void Trapsum(const Eigen::VectorXd &x, const Eigen::VectorXd &y, Eigen::VectorXd &z)
int Vlocate(double x, const V &xtab)
Referenced by CylDisk::get_dpot2, CylDisk::get_pot_dpot.
int Vlocate_with_guard(double value, const V &vec)